### ISSUE TITLE
Template XML file should should offer workspace-related location

### ISSUE THREAD

**Issue by findepi** [cbeust/testng-eclipse#102]
In the Template XML file configuration (either in workspace settings or in project settings) I'd like to refer to template file within workspace in a way that only relative path from workspace is stored in the configuration file.

This would allow, for example, committing shared setting to the repository along with other project configuration files.

**Comment by missedone** [comment]
another voice from SO: http://stackoverflow.com/questions/41622570/specifying-relative-paths-for-template-xml-file-in-testng

**Comment by missedone** [comment]
now the feature is available in latest beta update-site: http://testng.org/eclipse-beta, feel free to put your feedback here
