### ISSUE TITLE
testng-eclipse-plugin run configurations not check dependencies

### ISSUE THREAD

**Issue by yanshuai** [cbeust/testng-eclipse#104]
I found that sometimes testng-eclipse-plugin run configurations not check depedencies. for example, I have two class A and B, class A has a method named aMethod, and class B has a method named bMethod, A's aMethod depends on B's bMethod. When I want to run configurations=> run class A, the testng.xml generated won't include class B's bMethod, How can fix it?

**Comment by missedone** [comment]
this should be done in PR #345 (check dependesOnMethods on other classes), #347 (slightly performance improvement on checking dependencies).

you can verify with latest beta: http://beust.com/eclipse-beta

feel free to reopen it you still encounter issue. thx
