### ISSUE TITLE
Version of TestNG 6.8.6 eclipse plugin went from 6.8.6.20130914_0724 to 6.8.6.20141201_2240

### ISSUE THREAD

**Issue by nickboldt** [cbeust/testng-eclipse#109]
The version of the TestNG 6.8.6 eclipse plugin (and feature) went from 6.8.6.20130914_0724 to 6.8.6.20141201_2240.

There are two problems with this:

a) you can't have two different 6.8.6 releases, only one; so the second release ought to perhaps be 6.8.7 instead?

b) 20141201 is in the future (2014-Dec-01). If you meant 2014-Jan-12, then the datestamp should have been 20140112 per standard ISO date conventions. Using your yyyyddmm convention will cause confusion if you do a subsequent release on the 6.8.6 stream on, say, April 11, which according to OSGi rules would be considered an OLDER feature (20141104 < 20141201, even though 2014-April-11 > 2014-Jan-12).

There are three things you can do to ensure that future releases are always seen as newer than old ones:

a) use a letter prefix like "v" before the datestamp; this lets you fix an existing x.y.z.2014 release because OSGi sees x.y.z.v2014 as newer than x.y.z.2014, based on ASCII values for "v" and "2"

b) always use ISO dates, yyyymmdd or yyyy-mm-dd

c) always increment your service digit after doing a release, so you don't accidentally end up with TWO 6.8.6 release builds. :)

Therefore I recommend your next release be versioned something like:

6.8.7.v20140320 (assuming you built it tomorrow).

If I could figure out how your build system works (I'm guessing you use Eclipse PDE somehow w/ some custom Ant scripts), I'd throw you a PR for this change, but I can't find in which file you have 6.8.6 or the timestamp stored. Also couldn't find changelog/release notes for anything recent. Is that generated too?

Is this the file that defines your latest version?

https://github.com/cbeust/testng-eclipse/blob/master/META-INF/MANIFEST.MF#L5

If so, how are you forcing a new version into that file? 

Would you like to be able to build w/ Tycho+Maven? If so, I can look at making you a PR for that, but you'll have to point me at which code is used and which is build/releng/metadata/unused. 

Cheers,

Nick

**Comment by manandbytes** [comment]
> Would you like to be able to build w/ Tycho+Maven?
@nickboldt It's using Tycho now ;-)
