### ISSUE TITLE
TestNgPlugin ask three times for user input when ${string_prompt} is used in the launch configuration

### ISSUE THREAD

**Issue by johanra** [cbeust/testng-eclipse#110]
I have shared an project  (https://github.com/johanra/testng-launch-prompts-multiple-times) that reproduces the problem.
The project contains 4 launch configuration that all contain ${string_prompt:working directory}
MyApp.launch. (launches MyApp as a java program and only prompts once)
MyAppMavenBuild.launch (launces a maven build of the project and only prompts once)
MyAppTest.launch (launces MyAppTest as a TestNG test, this prompts 3 times)
MyAppTestSuite.launch (launches test-suite.xml and also prompts 3 times

I am using version 6.8.6.20141201_2240 of the TestNG plugin

**Comment by johanra** [comment]
When do you plan to release a version of the eclipse plugin that has this fix ?

**Comment by cbeust** [comment]
I just updated a new 6.9.7 plug-in, can you try it?

-- 
Cédric

**Comment by johanra** [comment]
Hi Cedric, the problem is fixed when using the latest plugin in Eclipse Luna SR2

**Comment by cbeust** [comment]
Great, thanks!
