### ISSUE TITLE
TestNg Eclipse-plugin and snakeyaml conflict

### ISSUE THREAD

**Issue by yeshvanthni** [cbeust/testng-eclipse#111]
TestNg uber jar that the plug-in ships has snakeyaml classes of a particular version in the testng uber jar and is conflicting with applications snakeyaml version. This renders any type of testing with Cassandra impossible as it uses yaml configuration and snakeyaml as its parser.

**Comment by ntabusca** [comment]
This makes impossible to test in eclipse spring boot apps with yaml configurations. Could you please address this in one of your next releases?

**Comment by cbeust** [comment]
Looks like shading the snakeyaml class files in the uberjar should take care of the problem.

**Comment by missedone** [comment]
in this case, you can enable "Use Project TestNG jar" so that your project defined version of testng will be used (for example, the testng version managed with the maven pom.xml)

**Comment by missedone** [comment]
with pr #224 (to be released in 6.9.11), testng plugin always uses project testng, wont append plugin embedded testng jar any more. 
so for most of cases, we wont see this kind of conflict.
