### ISSUE TITLE
TestNG properties on project should be documented

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#124]
TestNG properties on project is the only one screen which is not [documented](http://testng.org/doc/eclipse.html) yet.
Sadly, some properties are only located there (and it took me long time to find them).

**Comment by missedone** [comment]
@juherr @cbeust 
i'd like to help update the doc, how can I do that?
thanks

**Comment by cbeust** [comment]
The doc is in the `doc/` directory of http://github.com/cbehst/testng, just
send a PR from there.

-- 
Cédric

**Comment by juherr** [comment]
Maybe we can reconsider https://github.com/cbeust/testng/issues/635 too?

**Comment by cbeust** [comment]
I'll move the doc in its own repo and just pull it directly (which is what I do for Kobalt:  http://github.com/cbeust/kobalt-doc ).

**Comment by juherr** [comment]
:+1:
