### ISSUE TITLE
TestNG Eclipse releases should be sync with TestNG ones

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#125]
Until #122 won't be fixed, it could be useful to release TestNG Eclipse everytime a TestNG release is made.
Without that, we could be faced to situation where tests don't work because we use some TestNG features that are not available in the embedded TestNG.
For example: `ISuite#get/setParentInjector` which is available since **TestNG 6.8.8** and not in the **embedded 6.8.6**).

**Comment by cbeust** [comment]
Agreed, I need to update the Eclipse plug-in.

**Comment by missedone** [comment]
closed, since now the synchronization is a little bit easy with maven dependencies in commit: https://github.com/cbeust/testng-eclipse/commit/d2f5e66ec9b2ead08ba31ba35a17c25062be1468
