### ISSUE TITLE
Accents in class or method names cause "Debug as TestNG Test" menu item to do nothing.

### ISSUE THREAD

**Issue by cquezel** [cbeust/testng-eclipse#126]
In version 6.8.6.20141201_2240 having accents in class or method names cause "Debug as TestNG Test" menu item to do nothing.

    package bla;

    public class Accentué {

        @Test
        public void accentué() {

**Comment by missedone** [comment]
hi @cquezel 
could you try latest testng eclipse plugin, i don't see any issue:
<img width="634" alt="testng_aa" src="https://cloud.githubusercontent.com/assets/555134/12528789/826f27dc-c157-11e5-956c-972e10ad2582.png">

**Comment by cquezel** [comment]
All is fine in TestNG 6.9.10.201512240000
