### ISSUE TITLE
Setting a "test" package outside of "src".

### ISSUE THREAD

**Issue by LM450N** [cbeust/testng-eclipse#127]
Hello, I'm using _JUnit_ since few years and one thing is missing in _testNG_. I would like to create a specific __test source folder at the same level as src__ and not inside. The reason is my GWT compiler settings (who I don't want changed). Maybe I missed the configuration.

Does it possible to do this now ?

(sorry for my poor english)

**Comment by missedone** [comment]
testng-eclipse plugin does not prevent you from using any other source folder than 'src'.
in your case, you can simple right click on the 'test' folder, select "Build Path -> Use as Source Folder", also make sure you have testng lib/jar on your project classpath.

**Comment by missedone** [comment]
@LM450N 
please close this issue if you don't have any further question, thanks
