### ISSUE TITLE
Results View not synchronizing properly

### ISSUE THREAD

**Issue by eliasbalasis** [cbeust/testng-eclipse#129]
Under Luna (4.4.2 both 64 and 32 bit) on Windows 7 (64-bit),

When running a series of tests with "Results" view open on "All Tests" page the tests complete but the "Results" view often still displays the test is still executing (red square button on top)

The problem does not occur when on "Summary" page instead.

Some UI synchronization issue perhaps?

**Comment by stephenh** [comment]
I have something similar to this, in Mars.2 Release (4.5.2), the tests will be done, but the bar isn't changed to green. It just stays blank:

![image](https://cloud.githubusercontent.com/assets/6401/17080125/d9fe3304-50e9-11e6-9a55-63fb128daccf.png)

**Comment by eliasbalasis** [comment]
I confirm still happens with Mars 2 but I doubt it is Eclipse related, it has to be plugin related, I haven't tried with Eclipse Neon yet though. When on Summary" section however the problem does not occur.

**Comment by eliasbalasis** [comment]
I can also confirm this happens when many test methods run which involves scrolling anx gives me the impression of some sort of UI related sync issue or something similar

**Comment by missedone** [comment]
yes, it's definitely annoying, will look into this later.

**Comment by missedone** [comment]
hi guys
could you install and verify the latest snapshot of plugin from beta update-site: http://testng.org/eclipse-beta
thanks

**Comment by stephenh** [comment]
I've only poked at it for a few minutes, but it looks great!

Thanks Nick!

**Comment by missedone** [comment]
good to know, thanks
