### ISSUE TITLE
build testng eclipse plugin with tycho

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#133]
Hi
as it's quite easy to build plugin with tycho, it allow us to build plugins automatically on the command line as simple as `mvn -e clean install`
with this, we can also try to put the latest testng release jar into plugin to keep it's synced up.

but to facilitate with tycho, we need to restructure the plugin folders as below: ![sample](http://www.vogella.com/tutorials/EclipseTycho/images/xtychosetup10.png.pagespeed.ic.mV7FZnKSoF.png) 

if you think it worth to go, i can create a pull request.

see also:
[Eclipse Tycho for building Eclipse Plugins and RCP applications - Tutorial](http://www.vogella.com/tutorials/EclipseTycho/article.html)

**Comment by missedone** [comment]
@cbeust 
do you still use autobuild.plugin.xml to build testing-eclipse plugin?

i'm trying to refactor the folder structure to facilitate tycho, once it's done, i think you don't need `auto build.*` anymore

**Comment by cbeust** [comment]
No, I just build it from inside Eclipse.

**Comment by missedone** [comment]
closed as PR #135 was merged, thanks
