### ISSUE TITLE
how to export testng-eclipse that can work in kepler?

### ISSUE THREAD

**Issue by liefdiy** [cbeust/testng-eclipse#134]
I exported testng-eclipse as deployable plug-ins and fragments. Then I copied the jar into plugins folder of indigo, started eclipse.exe, TestNG worked.
But it failed in Kepler with the same method, I don't know why. can anybody help me please?
Thanks very much!

**Comment by missedone** [comment]
@liefdiy 
you can have a look at PR #135, this is still waiting to be merged, before that, you can git clone my code repo, and build with maven command `mvn -e clean package`, please see more details in https://github.com/missedone/testng-eclipse/blob/refactor/133/DEVELOP.md

**Comment by missedone** [comment]
@liefdiy 
Just FYI that PR #135 was merged, you can pull the latest code on master branch from cbeust/testng-eclipse

**Comment by missedone** [comment]
@liefdiy 
could you close this issue if you don't have any other question?
thanks
