### ISSUE TITLE
eclipse auto update for testng-eclipse (versions before 6.8.22) not work

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#136]
@cbeust 
people installed testng-eclipse 6.8.6.xxx won't auto update to the latest 6.8.22.xxx, as my PR #135 changed the feature id to `org.testng.eclipse.feature` from `org.testng.eclipse`, eclipse auto update manager trade them as two different features.

to bypass this issue, people can force update the plugin as below:

1. Click "Help -> Install New Software" from the top menu
2. Select "Update site - http://beust.com/eclipse" from the "work with" dropdown list, new version of testng-eclipse plugin 6.8.22 will be displayed. Select the "TestNG" plugin to install, and optionally uncheck the "Contact all update sites during install to find required software" to speed up the installation process. 
![figure-1](https://cdn.pbrd.co/images/dh181DI.png)
3. Now it show you old plugin will be uninstalled, click "Next"
![figure-2](https://cdn.pbrd.co/images/dfO87vJ.png)
4. Review the install detail, click "Next"
![figure-3](https://cdn.pbrd.co/images/dfPCspC.png)
5. Review the update detail, click "Next"
![figure-4](https://cdn.pbrd.co/images/dfRayd8.png)
6. click "Finish" to start install the new plugin 6.8.22
![figure-5](https://cdn.pbrd.co/images/dfSHOBO.png)

newly installed plugin since version 6.8.22 won't be affected.

so I think this should be documented somewhere to notice the existing plugin users.

**Comment by cbeust** [comment]
Thanks for the precision, Nick. I did the upgrade manually myself and it
worked exactly as you said.

I'm puzzled, though: I never noticed Eclipse plug-ins auto updating, and
I'm pretty sure 6.8.6 and below never did. Were they expected to?

Either way, I will soon be sending an email to the testng-users list to let
everyone know a new plug-in is available and that they should update
manually.

Also, does that mean that from now on, the new Tycho-based plug-in will
auto update?


-- 
Cédric

**Comment by missedone** [comment]
sorry for confusions, there're three ways to discover a new update of the plugin:
* Click "Help -> Check for Updates"
* or, configure "Automatic Updates" in eclipse preference: "Eclipse -> Preferences... -> Install/Update -> Automatic Updates", make "Automatically find new updates  and notify me" checked. Personally, i had this enabled. So be noticed that, *it's nothing with tycho* :)
* or, manually check the update site as i stated in figure-1 above.

as the testng eclipse feature id was changed to new one, approach 1 and 2 won't work any more since eclipse update manager trade the new feature id and the old one are two different thing, hence it won't notify new testng eclipse plugin available.

so the way out is approach 3 as detailed above, once people update to 6.8.22 or above, they won't have this update issue anymore:)

**Comment by cbeust** [comment]
Got it, somehow it never occurred to me to turn on auto updating for my
Eclipse plug-ins...


-- 
Cédric

**Comment by manandbytes** [comment]
> people installed testng-eclipse 6.8.6.xxx won't auto update to the latest 6.8.22.xxx, as my PR #135 changed the feature id to org.testng.eclipse.feature from org.testng.eclipse, eclipse auto update manager trade them as two different features.

Actually, there is a way to fix this issue (change in the feature ID). I could take a look and submit PR in a few days.

**Comment by missedone** [comment]
@cbeust 
after one night sleeping, I pivoting my view that, rather than change the feature Id, I changed the groupId of the feature artifact
now the generated update-site with feature Id back to the origin one 'org.testng.eclipse.feature.group' as 6.8.6.xxx
please see more details in PR #136

@manandbytes 
please kindly review  the code change as well share the idea of any better solution, thanks:)

**Comment by cbeust** [comment]
Yup, I merged it and I'm playing with it right now. I reimported the
project in Eclipse but somehow, Eclipse is not recognizing any of the
source files as a source file. Not sure what's going on.


-- 
Cédric

**Comment by missedone** [comment]
please delete your projects from workspace, and "Import -> Existing Projects into Workspace".
if it does not work, you can backup your current local testing-eclipse project and git clone from master, and re-import again.
i suspect that there could be some change in the .classpath on your local?

**Comment by cbeust** [comment]
I did all this, Eclipse is still confused, even saying that the project I
just freshly reimported "doesn't exist" when I try to jump to a symbol :-)

I even switched workspaces to start afresh, same thing. I'm investigating.



-- 
Cédric

**Comment by cbeust** [comment]
I installed a new Eclipse, switched to a new workspace, imported `testng-eclipse` and when I try to `F3` to a symbol, I get:

![image](https://cloud.githubusercontent.com/assets/92322/7466342/bc0c1e28-f295-11e4-8e66-02c91e332ec9.png)

Mystifying.

**Comment by missedone** [comment]
interesting, which eclipse version you used.

i tried at my side with eclipse-standard-luna
1. git clone from your master branch
2. create new workspace
3. import existing projects into workspace

everything works fine...
