### ISSUE TITLE
Eclipse update site unaccessible

### ISSUE THREAD

**Issue by kkarski** [cbeust/testng-eclipse#139]
I am getting a HTTP 403 Forbidden error when trying to download the plugin from the eclipse site:

http://beust.com/eclipse/

The error I get in Eclipse when installing from Marketplace:
The following solutions are not available: TestNG for Eclipse

**Comment by cbeust** [comment]
Mmmh, the update site works fine from my site (http://beust.com/eclipse) but you're right that installing from the Eclipse market place fails.

@missedone Any idea?

**Comment by cbeust** [comment]
I tried to update the feature id on the marketplace (from `org.testng.eclipse` to `org.testng.eclipse.feature`) but that didn't fix the problem:

![image](https://cloud.githubusercontent.com/assets/92322/7482778/b7ea4e8e-f32e-11e4-9ea6-4c401ed50072.png)

**Comment by missedone** [comment]
@kkarski
this should be resolved, could you verify and close this issue?
thanks

**Comment by kkarski** [comment]
Yes. Works fine now.
