### ISSUE TITLE
Timeout while trying to contact RemoteTestNG.

### ISSUE THREAD

**Issue by pankajgakhar** [cbeust/testng-eclipse#144]
Just installed the testng eclipse plugin (6.9.0.201505070412	) and not able to run the tests now. I am getting the error as shown in this screenshot.

![screen shot 2015-05-09 at 1 55 25 pm](https://cloud.githubusercontent.com/assets/3160339/7549470/611ef1f4-f653-11e4-9a49-e1cb76b9e95c.png)

**Comment by pankajgakhar** [comment]
I tried updating to latest testng.6.8.21.jar available in maven repo. Still the same error.

**Comment by missedone** [comment]
@pankajgakhar 

could you try run with "Use project TestNG jar" enabled:
right click on the project -> Properties -> TestNG -> enable "Use project TestNG jar"
with this settings, testng eclipse plugin will respect your project classpath, otherwise the plugin will inject plugin-embedded testng jar (version of 6.9.0-SNAPSHOT) to the launch classpath

please let's know if this works for you or not, thanks

**Comment by pankajgakhar** [comment]
Indeed, the tests started running by checking that checkbox. But, the Results view in eclipse is blank and getting this error in the logs after tests are run.

java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:92)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:136)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1864)
	at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1773)
	at java.io.ObjectOutputStream.<init>(ObjectOutputStream.java:229)
	at org.testng.remote.strprotocol.SerializedMessageSender.sendMessage(SerializedMessageSender.java:24)
	at org.testng.remote.strprotocol.MessageHub.sendMessage(MessageHub.java:44)
	at org.testng.remote.RemoteTestNG$RemoteSuiteListener.onFinish(RemoteTestNG.java:250)
	at org.testng.SuiteRunner.invokeListeners(SuiteRunner.java:200)
	at org.testng.SuiteRunner.run(SuiteRunner.java:243)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)

**Comment by missedone** [comment]
thanks for reporting back, could you create a small project for us to reproduce this issue?
you can share the small sample project on github or cloud driver? 
thanks

**Comment by pankajgakhar** [comment]
@missedone 

I was missing the dependency org.beanshell:bsh:2.0b4 required by testng-6.8.21.jar. After adding this dependency I am able to see the results in the Results view. 

Thanks for the quick response.

**Comment by missedone** [comment]
@pankajgakhar 

great, i created PR #145, added bsh to launch classpath

**Comment by cbeust** [comment]
I just deployed a new plug-in with Nick's fix, can you update and try again?

-- 
Cédric

**Comment by pankajgakhar** [comment]
After using the override of Use Project's TestNG jar,
1. If I use the testng version 6.8.21 it works fine. The Results view shows the data (passed/failed tests). 
2. If I use the testng version 6.8. The tests get executed but the Results view doesn't show anything and SocketExceptions are seen in the logs.

**Comment by missedone** [comment]
@cbeust do you have any insight?

from my view, it could be the compatibility issue as i stated in #122:
> Howerver, please also be aware that, the original reason to disable "use project testng jar" was to make sure the the plugin embedded testng jar be compatible with the runtime testng, as plugin launch the test suite with remotetestng class, that said plugin acts as the client that receive result from testng server.
> Now by enabling use project jar by default will expose the potential compatibility risk in future

**Comment by vahchil** [comment]
I'am having the same issue with the latest testNG eclipse plugin 6.9.5.201505260426.
The tests get executed after enabling "use project testng jar ",but the Results view doesn't show anything and SocketExceptions are seen in the logs.
Disabling the "use project testng jar" cannot launch the tests.
Which version of testNG eclipse plugin is this fix available in?

**Comment by missedone** [comment]
@vahchil 
what's the JDK version you used for running Eclipse and launching the test cases?
could you make the version consistent, both 1.7 or both 1.8.
as the test results are marshalled/unmarshalled with objectinputstream via socket between plugin and testng runtime

**Comment by vahchil** [comment]
Initially I was using JDK 1.6 for both, now changed to use 1.7.0_79 for
both, but still seeing socket exceptions and testNG results tree is blank.

**Comment by missedone** [comment]
@vahchil 
could you try with latest snapshot of testng: 
https://oss.sonatype.org/content/repositories/snapshots/org/testng/testng/6.9.5-SNAPSHOT/

still, everything running with JDK 1.7
thanks

**Comment by missedone** [comment]
@vahchil testng 6.9.6 was released to maven central week ago, could you try with this version see if the issue happen again thanks

**Comment by gatschet** [comment]
I had the sama problem. After update to 6.9.6 it works like a charm.

**Comment by vahchil** [comment]
How do i install this from maven central as an eclipse plugin?

**Comment by missedone** [comment]
@vahchil,
 for now, the recommended version baseline is as below:
* TestNG: 6.9.6, get from central maven repo
* TestNG Eclipse Plugin: 6.9.5 the latest, get from testng eclipse plugin update site: http://beust.com/eclipse
* JDK for both running TestNG and TestNG Eclipse Plugin: 1.7 or above, please make sure the version consistent.

if you still encounter the socket "Broken pipe" issue, could you take a look at this comment:
https://github.com/cbeust/testng-eclipse/issues/91#issuecomment-126371813
it'll be appreciated if you can report back the result, thanks:)

**Comment by cbeust** [comment]
@missedone I think you forgot one step:

- Tell Eclipse to use the project's testng.jar (6.9.6) instead of its own (6.9.5)

I'll push an updated 6.9.6 Eclipse plug-in soon.

**Comment by pbouillet** [comment]
I have the same problem here that I always get the connection timeout popup and tested all of the comments above (using testng 6.9.6 etc.). My test setup needs some time to start up and it seems like he is just waiting for 3 or 4 seconds? Is there any way to configure how long he will wait until the error is thrown? The old versions of testng with old eclipse versions were running fine with the same tests.

**Comment by missedone** [comment]
@pbouillet 
for now, it just waits for 5 sec, and not configurable at the moment:

```java
  public void initReceiver() throws SocketTimeoutException {
    if (m_inStream != null) {
      p("Receiver already initialized");
    }
    ServerSocket serverSocket = null;
    try {
      p("initReceiver on port " + m_port);
      serverSocket = new ServerSocket(m_port);
      serverSocket.setSoTimeout(5000);

	  Socket socket = serverSocket.accept();
	  m_inStream = socket.getInputStream();
...
}
```

do you have a lot staff in static initializing in your tests?

@cbeust 
in this case, make timeout configurable might just works for @pbouillet , but consider along with issue #155, we need a ultimate solution.

**Comment by pbouillet** [comment]
@missedone 
> do you have a lot staff in static initializing in your tests?

Yes, in some way. The tool I'm working on is using a javaagent based approach to instrument methods. And there is some initialization involved which is executed before the whole test + testng is executed. Thus it can take (even on my performance laptop) several seconds until the test will really begin. A configurable timeout would really work for me here.

I just wonder, was this changed to be lower? Because in the past I had never had such an issue with starting my test.

**Comment by JnRouvignac** [comment]
This is definitely something that can happen.
I remember having the first JVM run of a unit test taking 8s just for class loading (there were a lot of them).
Since it was unbearable, I then refactored the code to only load what was necessary for the test.

**Comment by missedone** [comment]
i'm working on the fix now, will create a PR later
the fix suppose to fix #155 as well

**Comment by missedone** [comment]
@cbeust, 
could you take a look at the eclipse plugins side PR: https://github.com/cbeust/testng-eclipse/pull/166

if it's OK, once it's merged, i think we might need a snapshot build for testng eclipse plugin, and ask people help verify issue #144 and issue #155 
thanks

**Comment by cbeust** [comment]
Just one typo and I'll merge, @missedone. Thanks again for working on this!

**Comment by missedone** [comment]
hi guys, new testng eclipse plugin build 6.9.5.201508210528 was just out, could you update to this version and verify if this issue resolved, thanks

**Comment by rajendraalagundi** [comment]
Face the same issue.

The issue was resolved by deleting the older versions testng.jar files from  
mvn repository /Users/{username}/.m2/repository/org/testng.So keep one testng.jar in repository.

I seems there was ambiguity caused by presence of multiple testng.jar files.

**Comment by missedone** [comment]
@rajendraalagundi 
what's the exact issue you encountered?
is it ".SocketException: Broken pipe" or "Timeout while trying to connect RemoteTestNG"?
they are different issues.
