### ISSUE TITLE
Plugin declares ExecutionEnvironment J2SE-1.5, but needs Java7 because of testng.jar

### ISSUE THREAD

**Issue by rakus** [cbeust/testng-eclipse#149]
The eclipse plugin 6.9.5 states that is needs J2SE-1.5, but the file testng.jar packaged with the plugin was compiled with Java7 producing classes with targetCompatibility 1.7 (class version 51.0).

The plugin installs fine on my machine, but fails at runtime as I  have only Java6 available.

Does testng require  targetCompatibility 1.7? 
If yes, the plugins Bundle-RequiredExecutionEnvironment should be set accordingly.
If no, testng should be compiled with the correct targetCompatibility.

**Comment by cbeust** [comment]
The minimum is 1.7.

**Comment by rakus** [comment]
It would be great to document java prereqs somewhere. Perhaps on the download page.

For the records: 
The older eclipse plugin 6.8.22 works with Eclipse Luna and Java6.
Update-Site: http://beust.com/eclipse-old/eclipse_6.8.22.201505070320

**Comment by weisljl89** [comment]
I know,So that's it! # 151 issue encountered the same problem
