### ISSUE TITLE
Add Java Editor Template - for quickly adding a new test method

### ISSUE THREAD

**Issue by verhagen** [cbeust/testng-eclipse#152]
Eclipse supports (Java editor) templates. To quickly add a new TestNG annotated test method, a tempalte like the one below would be nice to have.

	@${testType:newType(org.testng.annotations.Test)}
	public void ${testName}() throws Exception {
		${staticImport:importStatic('org.testng.Assert.fail')}${cursor}
		fail("Not yet implemented");
	}

This template can be added by hand as well.

  - Go to the Eclipse _Preferences_
  - Select from the tree on the left: Java > Editor > Templates
  - Use button _New..._ (on the right)
  - Enter the values:

	Name: __testng__
	Description: __test method (TestNG)__
	Context: __Java type members__
	Automatically insert: __Disabled__
	Pattern:

		@${testType:newType(org.testng.annotations.Test)}
		public void ${testName}() throws Exception {
			${staticImport:importStatic('org.testng.Assert.fail')}${cursor}
			fail("Not yet implemented");
		}

**Comment by missedone** [comment]
thanks @verhagen , i just created a PR #153 based on your template

**Comment by onlinegeek101** [comment]
Question does the merge build it out to the update site? If not when will this be available in the update site distrobution.

**Comment by cbeust** [comment]
@missedone @onlinegeek101 I just uploaded it to the update site, can you try it and report back?

**Comment by onlinegeek101** [comment]
Worked. Thanks for response.

**Comment by missedone** [comment]
works for me too, could you close this issue, thanks
