### ISSUE TITLE
Add Eclipse Favorites - for static import of org.testng.Assert.*

### ISSUE THREAD

**Issue by verhagen** [cbeust/testng-eclipse#154]
It would be nice to have the **Assert static imports** available under _Content Assist Favorites_. Added by the TestNG plug-in. If the **Assert static imports** are available in that way, importing a static method is easier, as they appear on top of the suggestion list.

Like when coding

```
@Test
public void someTest() throws Exception {
    assertEq<press suggestion keys>
}
```

_I've no idea if it is possible to create an Favorites entry, by another plug-in._

The action plan below, shows how it is done manually.

**Action Plan**
- Use Eclipse menu: _Windows > Preferences_ (On OS-X menu: _Eclipse > Preferences_)
- The _Preferences_ dialog opens
- Select from the tree on the left: _Java > Editor > Content Assist > Favorites_
- Use the button **New Type...**
- Now the dialog _New Type Favorite_ is opened
- Use the button **Browse...**
- Now the dialog _Type Selection_ is opened
- Enter in the text field _Choose type name_ the value _Assert_
- The list _Matching items_ shows all `static` classes, that are found.
- Select the one from `org.testng`
- Press the **OK** button
- Press the **OK** button
- The _Preferences_ dialog should now show an extra entry in the _Favorites_ list like `org.testng.Assert.*`

**Comment by missedone** [comment]
@verhagen 
As there is no official plugin extension point for adding new "favorite static import", though I know there's way to hack that (such as programmatically add testng static import into the PREF_CODEASSIST_FAVORITE_STATIC_MEMBERS preference store), however i don't like the hack that it just make the code necessary complex.

so the short answer is, no, i don't think we can support this at the moment, please manually add it.
thanks

**Comment by missedone** [comment]
@verhagen, the feature is available in latest beta now: http://beust.com/eclipse-beta
thanks

**Comment by missedone** [comment]
now the static import `org.testng.Assert.*` will be added when Eclipse startup, if people manually remove it from the preference, it won't be added again.
