### ISSUE TITLE
Distinguish test class instances when using Factory

### ISSUE THREAD

**Issue by nemesis13** [cbeust/testng-eclipse#167]
## Problem description
When using a Factory the Eclipse Plugin merges the test results in the view, making it almost unusable. If a test method fails at first and succeeds at second try, the graphical representation of the method will be first painted red and then green. This applies also the other way around and to any number of runs - the last run being the one displayed at the end. The stacktrace is still visible when clicking on the entry, but only for the last failure.

## Objective
Detect whether a test class is instantiated with parameters and couple the params with the instance in the view. This has been done with methods that use DataProvider already.

## Workaround:
When the test class has a toString() that returns different strings per instance, the results are drawn nicely.

**Comment by cbeust** [comment]
+ @missedone

**Comment by missedone** [comment]
@nemesis13 
could you share a simple project to reproduce this, though i can take some time to reproduce as well, however, this can help me understand the problem and make the life easy
thanks

**Comment by nemesis13** [comment]
Sure. Sorry for the long wait. Here's an example class. If you run it using eclipse you'll see the first test result as green, the second one as red and the third one marks the test method as green and leaves the class red. The stacktrace of the last failed run (and only the last) can be viewed when clicking on the green test method in the TestNG overview. If you remove the comment marks around toString() the plugin will see different names for each instance and render the objects correctly, i.e. separately. Consider the included screenshots for comparison.

![without-tostring](https://cloud.githubusercontent.com/assets/278624/10247528/12a614f0-691a-11e5-9284-a18821fd65af.png)
![with-tostring](https://cloud.githubusercontent.com/assets/278624/10247533/1a2e6fe2-691a-11e5-8030-d30577156218.png)

    package com.trustedshops.bugreport;
    
    import org.testng.annotations.DataProvider;
    import org.testng.annotations.Factory;
    import org.testng.annotations.Test;
    
    public class TestA
    {
        
        private int n;
    
        @DataProvider(name = "dp")
        public static Object[][] dp()
        {
            return new Object[][] {{1}, {2}, {3}};
        }
        
        @Factory(dataProvider = "dp")
        public TestA(int n)
        {
            this.n = n;
        }
        
        @Test
        public void test1() throws InterruptedException
        {
            Thread.sleep(1000);
            assert (n != 2);
        }
        //public String toString()
        //{
        //    return String.valueOf(n);
        //}
    }

**Comment by missedone** [comment]
hi @nemesis13 
fixed in #172, could you have a look if that solve your problem, thanks

**Comment by nemesis13** [comment]
Tested and it works - you can now see all results without any overriding.

I think it might look better if the class instance was displayed multiple times though, as it is when overriding toString(), only with the class name. But I guess it's hard to distinguish arbitrary instances in Java since AFAIK there's no built-in object IDs or the like. This would come handy especially when using data providers on methods. I've attached two screenshots with a data provider used on the only test method. On the first screenshot it's hard to tell which instance a method belongs to. If you separate the instances in the view, however, you can clearly see that all runs of one instance failed.

But as said before I consider this hard to implement and rather a rarely used luxury feature ;-)

After this patch:
![eclipse-testng-bug2](https://cloud.githubusercontent.com/assets/278624/10340006/5f0c538e-6d0e-11e5-81ec-076e4c250c7d.png)
After this patch with toString on class:
![eclipse-testng-bug1](https://cloud.githubusercontent.com/assets/278624/10340007/5f0ddd44-6d0e-11e5-8235-4bacb41cab82.png)

**Comment by missedone** [comment]
right, 'd rahther llike you to override tostring in your case since it is by designed that leave you a way to decide the display name:)
see also my descriotion in pr #172
btw, please close this issue if you think it is ok now
thanks

**Comment by nemesis13** [comment]
Okay. I understand that for the Plugin two instances are one if the instance names are the same. It's sub-optimal to have a different representation of class instances depending on their string representations, though. E.g. the screenshots above both are suposed to show the same hierarchy and still it looks all different only because of a toString method.

Just my two cents.
BTW This doesn't affect the fact I'm very thankful for your hard work! Keep it up!
