### ISSUE TITLE
running TestNG with the 'argLine' of maven-surefire-plugin from pom.xml by default

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#168]
when i use IntelliJ testng plugin to run my test cases, it's smart enough that load the 'argLine' of maven-surefire-plugin from the project pom.xml by default if it's present. this save me a lot of time from editing the run configuration by appending the JVM arguments.

i'd like to see this feature for testng eclipse plugin as well

**Comment by missedone** [comment]
here is the behavior for different scenario we need discuss:
1. no pom.xml ---> do nothing
2. pom.xml exists, but no maven-surefire-plugin or maven-safefail-plugin, in essential, no "<argLine>" element tag at all in the pom.xml ---> do nothing
3. if there is one "<argLine>" element tag ---> append to the runtime testng JVM arguments, but do not display on the run/debug configuration
4. if there are more then one "<argLine>" element tag, for example, in case of multi <execution> or multi <profile> ---> use the first one?
5. add new flag to preference, allowing user to disable this auto-discover from pom.xml in case this feature annoying them:(

any thoughts?

**Comment by missedone** [comment]
@juherr
do you have any expectation for this?
any input is appreciated 
thanks

**Comment by missedone** [comment]
for case-4 " if there are more then one "<argLine>" element tag, for example, in case of multi <execution> or multi <profile>", i'm not quite sure how IntelliJ handle this, the result testng runtime JVM arg is none of the ones in pom.xml, maybe it just ignores the settings.

**Comment by juherr** [comment]
I wasn't aware about this feature as I don't use 'argLine'. I think it should work as IntelliJ because it easier to explain. 
Maybe you can ask them how it works by opening an issue.

**Comment by missedone** [comment]
this whole feature was completed in #193
