### ISSUE TITLE
Configurat test-output folder located under target in case of m2eclipse

### ISSUE THREAD

**Issue by khmarbaise** [cbeust/testng-eclipse#17]
I would suggest to change the default configuration for the test-output directory of the testng plugin in eclipse to target/test-output in case you are in a maven project in relationship with m2eclipise. I don't know if this is possible...

**Comment by missedone** [comment]
closing this issue since the test-output dir is configurable as below:

<img width="610" alt="tetsng-output" src="https://cloud.githubusercontent.com/assets/555134/10508346/577fe1b2-72db-11e5-8a59-48b2c901a2c7.png">
