### ISSUE TITLE
TestNG eclipse plugin seems to not taking the JDK from project

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#185]
@missedone I don't know if you are already know of it, but I've already seen users complaining about similars issues: http://stackoverflow.com/questions/33475970/error-while-running-testng-test

**Comment by missedone** [comment]
the runtime JRE of testng process is defined in the JRE tab:
<img width="686" alt="testng_jre" src="https://cloud.githubusercontent.com/assets/555134/11591601/e5c3afdc-9a4d-11e5-80c0-c0445d3298b3.png">

here is the correct answer for this question.

**Comment by juherr** [comment]
:+1:
