### ISSUE TITLE
can't find phantomjs on Windows

### ISSUE THREAD

**Issue by markdbullock** [cbeust/testng-eclipse#198]
My Eclipse TestNG plugin v6.9.9 was working fine with PhantomJS in Eclipse Luna on Windows 7.

I upgraded to the TestNG plugin v6.9.10 today.
When I ran a test suite, I got the following exception when creating a new PhantomJSDriver object specifying capabilities.

java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html

I worked around that error by specifying the path for PhantomJSDriverService.PHANTOMJS_EXECUTABLE_PATH_PROPERTY

Then I got the following error when calling WebDriver.quit()
java.lang.UnsatisfiedLinkError: Failed to create temporary file for /com/sun/jna/win32-x86-64/jnidispatch.dll library: Access is denied

Seems like it thinks I'm on a *nix system.

I worked around that by specifying -Djava.io.tmpdir=c:\temp

Then I got the following error in WebDriver.quit()
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'QAW7DOP917-PC', ip: '192.168.103.234', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_60'
Driver info: driver.version: RemoteWebDriver

**Comment by markdbullock** [comment]
I can run my test suite from the command line and all the tests pass.

**Comment by cbeust** [comment]
Another issue that seems to be related to `java.io.tmpdir`.

@missedone, any thoughts?

**Comment by missedone** [comment]
yes, this shares the same root cause as https://github.com/cbeust/testng/issues/903

fixed in PR #199

**Comment by cbeust** [comment]
I just deployed @missedone's fix.

**Comment by markdbullock** [comment]
I installed the new version and everything's green now.
Thanks very much!

**Comment by missedone** [comment]
tracking similar issue of JDT in bugzilla: https://bugs.eclipse.org/bugs/show_bug.cgi?id=413514
