### ISSUE TITLE
When testing using a suite should be able to select one (or more) tests (named by their tag)

### ISSUE THREAD

**Issue by david-bakin** [cbeust/testng-eclipse#201]
Maybe I just can't figure out how to do it, but when running a TestNG suite, within Eclipse, from a testing.xml file, I don't see a way in the run configuration window to specify a subset of all the named tests (`<test>` tags) to run.

**Comment by missedone** [comment]
no, it does not support in a straightforward way, but i think you can achieve this by:
1. select the testng test suite xml file on the "TestNG" tab on launch configuration page.
2. switch to "Arguments" tab, add command line arguments `-testnames` like this:
![testng201](https://cloud.githubusercontent.com/assets/555134/11556714/6f28ef9a-995d-11e5-9f37-4d58b5ec9ee4.png)

**Comment by kpassoubady** [comment]
The other approach to run individual test.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="ShapeSuite" parallel="false">
	<test name="ShapeTest">
		<groups>
			<run>
				<include name="area" />
				<include name="perimeter" />
				<include name="functional" />
			</run>
		</groups>
		<classes>
			<class name="com.kavinschool.shape.SquareGroupTest" />
		</classes>
	</test> <!-- Test -->
</suite> <!-- Suite -->
```
Look at the sample, you should provide the include with name attribute to run a specific testng groups. You need to have a unique group name for each of your test case, so you can include or exclude to run within your testng.xml.
