### ISSUE TITLE
testng-eclipse with M2E is failing with non maven projects

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#206]
See 
http://stackoverflow.com/questions/34050615/testng-an-internal-error-occurred-during-launching/34070227#34070227
or
http://stackoverflow.com/questions/34081538/testng-does-not-run-shows-java-lang-nullpointerexception
or
http://stackoverflow.com/q/34083687/4234729

**Comment by missedone** [comment]
fixed in PR #207 

CC: @cbeust

**Comment by juherr** [comment]
:+1:

**Comment by juherr** [comment]
@cbeust Could you create a `testng-eclipse` tag on StackOverflow? I've no enough reputation to do it myself :(

**Comment by cbeust** [comment]
Done: http://stackoverflow.com/questions/tagged/testng-eclipse

**Comment by cbeust** [comment]
#207 merged.

**Comment by juherr** [comment]
:+1:
