### ISSUE TITLE
"TestNG M2E Integration (Optional)" plugin was not available on Eclipse Marketplace

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#223]
it looks like the "TestNG M2E Integration (Optional)" plugin was not available on Eclipse Marketplace, it only shows TestNG plugin itself:
<img width="547" alt="testng_epp" src="https://cloud.githubusercontent.com/assets/555134/13031270/3c8a742a-d27c-11e5-8e43-06e31b45900d.png">

but if i install via "Help -> Install New Software..." then paste the update site url: http://beust.com/eclipse, both plugins are listed.
<img width="655" alt="testng_install" src="https://cloud.githubusercontent.com/assets/555134/13031275/a6fc1912-d27c-11e5-859b-6d23518e5ca8.png">

**Comment by missedone** [comment]
hi @cbeust 
i remember you fixed this before, but looks like it happens again?

**Comment by cbeust** [comment]
I don't really remember fixing this explicitly. As far as I understand it, the Eclipse Market place simply regularly polls my update site (http://beust.com/eclipse) so the M2E integration should appear there automatically.

**Comment by missedone** [comment]
hi @cbeust 
could you login Eclipse Marketplace, click "Edit" of the produce (TestNG plugin), and double check if the optional m2e integration is in the Feature IDs list, something like this:

<img width="719" alt="testng_emp" src="https://cloud.githubusercontent.com/assets/555134/13033457/5f9c1e9c-d2cb-11e5-8d9c-3157c68626c1.png">

**Comment by cbeust** [comment]
I just added `org.testng.eclipse.maven.feature` as an optional feature in
the Eclipse market place. I can't see any changes but maybe it takes a few
hours to update.

Let me know if this fixed it!


-- 
Cédric

**Comment by missedone** [comment]
yes, I can see it now, but could you make the "Install State" as `Optional - Selected` for `org.testng.eclipse.maven.feature` , so that by default it's selected on the list?

**Comment by cbeust** [comment]
It already is optional:

![image](https://cloud.githubusercontent.com/assets/92322/13034597/8589bf56-d2ee-11e5-8f68-e46b56a31a1e.png)

**Comment by missedone** [comment]
you can click the dropdown list and select **"Optional - Selected"**,
in this way, m2e integration plugin will be "checked/selected" by default when user trying to install TestNG for Eclipse from Marketplace.

<img width="708" alt="testng_emp_option_selected" src="https://cloud.githubusercontent.com/assets/555134/13037170/00693d46-d330-11e5-8218-d26015ddc50e.png">

**Comment by cbeust** [comment]
Oh I had missed that!

Fixed.

**Comment by missedone** [comment]
thanks, verified.
