### ISSUE TITLE
remove option "Use Project TestNG jar", to always use Project TestNG

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#224]
hi @cbeust 
from my understanding, the option "Use Project TestNG jar" is to solve the issue of communicating between IDE and TestNG process, e.g. issue #91 , etc. (please correct me if i'm wrong :smile: ).
this also can eliminate issue #111 "TestNg Eclipse-plugin and snakeyaml conflict" as along as people don't use "TestNG Library"

however, the option leads to confusion about which TestNG jar used at runtime for some users.

now that, we have abstracted the remote communication into testng-remote, i think it's time to remove this option to ALWAYS use project TestNG jar, do NOT append plugin embedded TestNG onto runtime process in any case.

what do you think?

CC @juherr

**Comment by juherr** [comment]
:+1:

It is possible to detect if `testng.jar` is missing in the project and update the classpath of the eclipse project?
In this case, maybe the plugin can continue embed a `testng.jar` and add it by default when missing.

**Comment by missedone** [comment]
in the case of missing testng.jar on project classpath, the IDE will show compile error, and user have to fix that before launch test.

the plugin will still embed one testng jar in case people want to add "TestNG Library" container for their eclipse project, for example some project dont use maven or any other dep mgmt tool, etc. however, if people add "TestNG Library", its still project classpath. though i think peole rarely use this case today.

**Comment by juherr** [comment]
Ok, perfect for me then!

**Comment by cbeust** [comment]
@missedone Right on. This option was only there as a stop gap measure, but your (and @juherr)'s new implementation of the remote TestNG completely takes care of that. I'm fine with completely removing it.

On a related note, the IDEA Kobalt plug-in does all this dynamically: it ships with its own `kobalt.jar` but at start up, it checks to see if a newer one is available from the release web site and if there is one, it downloads it and uses it instead.

**Comment by jnhagelberg** [comment]
This change makes it so that now we cannot run our TestNG tests in Eclipse.  It always fails with this error:

6.1.1 is not a supported TestNG version

We don't really have the option of upgrading the TestNG version in the pom.xml.
