### ISSUE TITLE
Support of old eclipse versions

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#225]
Currently, the documentation says:

> You can use either the Eclipse Market Place or the update site:
> 
> * Select Help / Install new software.
> * Search for new features to install.
> * New remote site.
> * For Eclipse 3.4 and above, enter http://beust.com/eclipse.
> * For Eclipse 3.3 and below, enter http://beust.com/eclipse1.
> * Make sure the check box next to URL is checked and click Next.
> * Eclipse will then guide you through the process.

Is it true the TestNG plugin still support eclipse 3.4 (last update fev 2009)?

Maybe we can drop the support for old eclipse versions too ? http://wiki.eclipse.org/Simultaneous_Release

For my information, what are the difficulties to support old versions?

**Comment by cbeust** [comment]
Yeah, we can totally drop support for these old (very, very old) versions.


-- 
Cédric

**Comment by missedone** [comment]
I updated the CHANGE.md in PR #227 , how does that look :relaxed: ?

**Comment by juherr** [comment]
@missedone Nice! The next question to answer (maybe on https://github.com/testng-team/testng-team.github.io ?) will be: Which version, and how, to install if I'm stuck with Eclipse x.y?

**Comment by missedone** [comment]
sure thing, will update later
