### ISSUE TITLE
All Tests: Failure Exception: following asserts failed: string gets cut off in view

### ISSUE THREAD

**Issue by elbaloo** [cbeust/testng-eclipse#237]
### Expected behaviour
All text for the failed asserts should be displayed.

### Actual behaviour
String is being cut off and doesn't allow to be fully read but I noticed that right clicking the failed assert and selecting "Copy TestNG message" does actually copy the full string.

### Steps to reproduce
1. Using SoftAssert, configure several assertEquals(String, String).
2. Make sure that either actual and/or expected strings are long enough.
3. Execute asserts.

### Running Configuration
* Plugin Version: 6.9.9.201510270734
* (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")
* (Optional) Operating System: Windows 7 Enterprise

### Screenshot
![image](https://cloud.githubusercontent.com/assets/1116842/14003495/99bcbc90-f129-11e5-9029-12f22ecfff0a.png)

**Comment by missedone** [comment]
hi @elbaloo 
unfortunately, this is an windows limitation: 
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=38519
* https://bugs.eclipse.org/bugs/show_bug.cgi?id=77711

it works quite well on OS X even i had a 1350 chars string.
