### ISSUE TITLE
snakeyaml loaded via testng plugin

### ISSUE THREAD

**Issue by neurolabs** [cbeust/testng-eclipse#24]
Hi,

we're using the plugin in version 6.1.1.20110728_1012. We're using snakeyaml 1.7 in our app. When running tests in eclipse (loading some test data via snakeyaml), the snakeyaml classes are not loaded from our classpath, but from the testng jar. Due to differing APIs, the test execution fails with a NoSuchMethodError.

Workaround: include the snakeyaml jar in the test classpath under bootstrap entries.

**Comment by missedone** [comment]
in this case, please follow @ryansmith4 's suggestion: https://github.com/cbeust/testng-eclipse/issues/24#issuecomment-23378221
