### ISSUE TITLE
tag the releases

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#240]
hi @cbeust 
TestNG Eclipse Plugin 6.9.11 was released, correct?

can we tag it in git and bump the version to next development phase.
also, maybe we can augment the release script for auto tagging (or, using maven release plugin)?

**Comment by cbeust** [comment]
Done. And sure, it would be better to update the release script as well.

**Comment by missedone** [comment]
the tag was on the wrong git revision, i just fixed.
