### ISSUE TITLE
How to install TestNg on amazon aws linux box?

### ISSUE THREAD

**Issue by shruthitest** [cbeust/testng-eclipse#250]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Running Configuration
* Plugin Version: 
* (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")
* (Optional) Operating System:

**Comment by missedone** [comment]
i'm not sure anything special on AWS linux box that prevent you from installing eclipse normally.
Hope this doc help you? http://testng.org/doc/download.html

**Comment by missedone** [comment]
please reopen if you still encounter the issue.
