### ISSUE TITLE
Classes from WAR project exported with `<attachClasses>true</attachClasses>` are not visible

### ISSUE THREAD

**Issue by michaldo** [cbeust/testng-eclipse#251]
### Expected behaviour
Classes (`my.MyClass`) from WAR project exported with option `<attachClasses>true</attachClasses>` and imported with
 ```
 <dependency>
     <groupId>testng-eclipse</groupId>
     <artifactId>my-war</artifactId>
     <version>0.0.1-SNAPSHOT</version>
     <type>jar</type>
     <classifier>classes</classifier>
</dependency>
```

should be visible when test is called by testng eclipse plugin

### Actual behaviour

> java.lang.NoClassDefFoundError: my/MyClass
	at my.MyTest.f(MyTest.java:8)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
(...)
Caused by: java.lang.ClassNotFoundException: my.MyClass
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)

### Steps to reproduce
1. Create WAR project with class my.MyClass and `<attachClasses>true</attachClasses>`
2. Create test project with dependency declared as above
3. Create test with instruction `new MyClass()`
4. Run test from Eclipse

### Running Configuration
* Plugin Version: 6.9.11.201604020423
* (Optional) Operating System: Win10

**Comment by missedone** [comment]
hi @michaldo 
could you verify it by installing the latest beta version of testng eclipse: http://testng.org/doc/download.html

**Comment by michaldo** [comment]
Cannot reproduce with version 6.9.12.201605281327

PS. I had to download brand new Eclipse to reproduce defect. On my usual Eclipse I can't reproduce it.
Anyway, big thanks

**Comment by missedone** [comment]
for people who encountering this issue, please install [m2e-wtp](https://www.eclipse.org/m2e-wtp/) plugin

**Comment by missedone** [comment]
the m2e-wtp plugin is out-of-the-box in Eclipse JEE Bundle, see details here: http://www.eclipse.org/downloads/packages/eclipse-ide-java-ee-developers/neon1a
