### ISSUE TITLE
Run as... default verbose level

### ISSUE THREAD

**Issue by travelbasys** [cbeust/testng-eclipse#253]
### Expected behaviour
The default Verbose Level should be 0.
An "ordinary" developer usually has no use for logging messages more appropriate for a TestNG committer.

### Actual behaviour
The actual verbose level appears to be 2.

### Steps to reproduce
1. Right-click a test class and select "Run as... TestNG Test"
2. Check the Console Tab.
3. It is quite full of logging messages in addition to normal test output.

### Running Configuration
* Plugin Version: 6.9.11

**Comment by missedone** [comment]
Hi @travelbasys
You can verify the fix with latest snapshot buold.
Thanks

**Comment by missedone** [comment]
now I set the default log level back to 2, since the test result, e.g. Exception of the assertion failure, are at level 2.
with PR https://github.com/cbeust/testng/pull/1175 merged, there is less log at level 2
