### ISSUE TITLE
Support multi versions for 'TestNG Library'

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#266]
first of all, 'TestNG Library' is this one on your project:
<img width="338" alt="testng_prj" src="https://cloud.githubusercontent.com/assets/555134/16610437/140a95c0-4310-11e6-86ba-26fb02b8d641.png">
(so you can ignore this ticket if you manage the project with maven or gradle or any other dependency management tool)

today, the jars of 'TestNG Library' are embedded in the plugin, which means the following things:
- there is only one version for it, and every time the TestNG released, there need to release a new plugin with the new jars as well.
- since the version of testng library bundled with plugin, when you update plugin (saying from 6.9.10 to 6.9.11) the testng version updated ass well, which might be unexpected.

I think one solution is to support multi versions for testng library, and allow user to select the version for the project in plugin.
as @juherr suggested before, we can download the testng jars from remote, or even better list local file system with a pattern of file structure (to be designed, my initial thought is to follow the maven repo layout)

please vote this feature, let me know, if you really want this feature, i will make it then 😄

**Comment by juherr** [comment]
:+1: I like the idea... if there still people who don't use dependency management tools :p

**Comment by cbeust** [comment]
I'm concerned that the amount of users who will benefit from this is very
low while the work is significant and potentially destabilizing.


-- 
Cédric
