### ISSUE TITLE
Add a rerun test key command/shortcut

### ISSUE THREAD

**Issue by stephenh** [cbeust/testng-eclipse#268]
JUnit has a rerun test command that I can bind to a key command, and it's very useful vs. having to always click to rerun the tests.

**Comment by missedone** [comment]
fixed in PR #269

be noted that, I added the command only, but NOT bind to any default shortcut, feel free to fill your favorite:
<img width="705" alt="rerun_testng_key_bind" src="https://cloud.githubusercontent.com/assets/555134/17078010/244e0f0e-509c-11e6-87e6-2d2aabf36ea0.png">

**Comment by missedone** [comment]
hi @stephenh 
could you install and verify the latest snapshot of plugin from beta update-site: http://testng.org/eclipse-beta
thanks

**Comment by stephenh** [comment]
Wow, that looks great, Nick, thanks!
