### ISSUE TITLE
[bintray] "Version 'latest' has been published more than 180 days ago and can no longer be deployed to."

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#280]
the direct result is people can't install the beta version of eclipse plugin, with error below in Eclipse:

```
Error
Sun Aug 28 20:09:53 PDT 2016
Artifact not found: http://testng.org/eclipse-beta/features/org.testng.eclipse_6.9.13.201608290215.jar.

java.io.FileNotFoundException: http://testng.org/eclipse-beta/features/org.testng.eclipse_6.9.13.201608290215.jar
    at org.eclipse.equinox.internal.p2.transport.ecf.RepositoryStatusHelper.checkFileNotFound(RepositoryStatusHelper.java:297)
...
```

when looking into the travis-ci job: https://travis-ci.org/cbeust/testng-eclipse/jobs/155685550

```
Processing ./artifacts.jar file...
Uploading p2 metadata file directly to the repository
{"message":"success"}
Processing ./content.jar file...
Uploading p2 metadata file directly to the repository
{"message":"success"}
Processing ./site.xml file...
{"message":"success"}
Processing features dir ./features/* file...
Processing feature: ./features/org.testng.eclipse_6.9.13.201608280606.jar file...
{"message":"Version 'latest' has been published more than 180 days ago and can no longer be deployed to."}
Processing feature: ./features/org.testng.eclipse.maven.feature_6.9.13.201608280606.jar file...
{"message":"Version 'latest' has been published more than 180 days ago and can no longer be deployed to."}
Processing plugin dir ./plugins/* file...
Processing plugin: ./plugins/org.testng.eclipse_6.9.13.201608280606.jar file...
{"message":"Version 'latest' has been published more than 180 days ago and can no longer be deployed to."}
Processing plugin: ./plugins/org.testng.eclipse.maven_6.9.13.201608280606.jar file...
{"message":"Version 'latest' has been published more than 180 days ago and can no longer be deployed to."}
Processing binary dir ./binary/* file...
Publishing the new version
{"files":0}
```

looks like we need to do something at bintray

**Comment by missedone** [comment]
as a workaround for now, I manually delete the version 'latest', and recreated it on bintray.
but this is annoying if we manually repeating the process every 180 days.

will try to see if any better way, e.g, with a automatic manner.

**Comment by juherr** [comment]
Why not having a version by deploy instead?

We may imagine having a dynamic redirection from http://testng.org/eclipse-beta to the latest version (by using https://bintray.com/docs/api/#_get_version )
Could you describe what could be the expected redirection?

I don't know if it will help because I don't understand everything, but I found http://www.lorenzobettini.it/2016/02/publish-an-eclipse-p2-composite-repository-on-bintray/

**Comment by missedone** [comment]
now the updatesite is in new layout since commit 7465f866

**Comment by de-jcup** [comment]
@missdone Hello I got the same problem with one of my plugins hosted at bintray and I checked out that you can simply "edit" the version and do an update (update button)! This fixed my problem and I was not forced to delete the "current" version. It seems the update action does reset the 180 days...

**Comment by de-jcup** [comment]
Today I had the same issue again... but with a new message:

> {"message":"Version 'current' has been published for more than 365 days. Files can only be uploaded
> to a version within 365 days from its publish date."}
> 

sorrowly updating the version does no longer solve the problem - so the workaround mentioned by myself in upper comment does no longer work :-(
