### ISSUE TITLE
Eclipse runner fails with 6.9.13

### ISSUE THREAD

**Issue by ben-manes** [cbeust/testng-eclipse#281]
I tried upgrading to `6.9.13` and received the following error in Eclipse,

>Exception in thread "main" java.lang.RuntimeException: Can't recognize the TestNG version on classpath. Please make sure that there's a supported TestNG version (aka. >= 6.5.1) on your project.
	at org.testng.remote.RemoteTestNG.getTestNGVersion(RemoteTestNG.java:123)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:38)

I checked for updates (none) and restarted Eclipse in case previous weren't applied. Unfortunately no luck. The installation details for the plugin are,

> TestNG  6.9.12.201607091356	org.testng.eclipse.feature.group	Cedric Beust

`6.9.12` works great, so I'll stick to that until this is resolved. Thanks!

**Comment by ben-manes** [comment]
Thanks for getting `6.9.13.1` pushed.

**Comment by missedone** [comment]
actually the latest is 6.9.13.2 now 😃

**Comment by Juju-Ong** [comment]
This issue closed?
