### ISSUE TITLE
Unable to download plugin

### ISSUE THREAD

**Issue by hmmlopez** [cbeust/testng-eclipse#283]
### Expected behaviour
1) I was able to download the plugin from the Eclipse Market place.
2) I think we supposed to be able to download also directly from the website (old versions)
http://beust.com/eclipse-old/

### Actual behaviour
Getting Forbidden, for example:
You don't have permission to access /eclipse-old/eclipse_6.9.12.201607091356/ on this server.

### Steps to reproduce
1. Fix the website http://beust.com for correct access.

### Running Configuration
* Using Eclipse Neon
* Behind proxy, but suppose to work through proxy configured in Eclispe -> Preferences -> Network.
* Eclipse Market places opens and I can search for the TestNG plugin and get result, when press install it starts downloading and then comes up with error described above.

**Comment by missedone** [comment]
hi @hmmlopez 

unfortunately, it's not available for direct download, which document [here](http://testng.org/doc/download.html)

> Note that the URL's on this page are update sites as well, not direct download links.

why do you want to download old versions? which version you want?
the workaround is, you can git clone the plugin source code, checkout from the tag, and build on your local.

**Comment by hmmlopez** [comment]
Access through Marketplace is not working for me, also tried the direct way by installing from the url in eclipse:

> Select Help / Install New Software...
> Enter the update site URL in "Work with:" field:
> Update site for release: http://beust.com/eclipse

Both way didn't work for me, so I guessed maybe it's the website. Can you check if it works for you to re-install it through Eclispe Marketplace? Maybe something is broken there. Few weeks ago I managed to download it without a problem.

I wanted to download the latest stable version, but since that was not working I was trying the older versions. For the older versions I didn't try to get them via update site, but to access them just through the browser.

**Comment by missedone** [comment]
I just did, install successfully from update site: http://beust.com/eclipse, the same one used by Eclipse Market Place.

**Comment by hmmlopez** [comment]
I think there is a bug in the Neon Eclipse, I was behind a proxy which requires authentication. It seems that Eclipse is opening marketplace and does everything correctly with proxy, but when it tries to download the actual jars (files) needed for the plugin it does not pass (or use) the proxy information which is why I get access denied. I had the same issue again, and connecting directly to internet without proxy worked fine.
