### ISSUE TITLE
Provide testng in the update site

### ISSUE THREAD

**Issue by mschreiber** [cbeust/testng-eclipse#287]
### Expected behaviour

The created p2 update site does contain the TestNG Eclipse Plugin but it does not contain the testng.jar as OSGi bundle although the testng.jar is an OSGi bundle. That would be helpful for someone who wants to use TestNG in a Tycho build to test Eclipse Plugins
### Actual behaviour

Only the Eclipse TestNG Plugin is provided in the p2 repository which does contain the testng.jar but that could not be used because the testng packages are not exported
### Steps to reproduce
1. 
2. 
3. 
### Running Configuration
- Plugin Version: 
- (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '**\* TestNG for Eclipse Details:' portion ")
- (Optional) Operating System:

**Comment by missedone** [comment]
good point, will do it soon
thanks for the proposal

**Comment by missedone** [comment]
hi @mschreiber 
i just read your article: http://www.mschreiber.at/eclipse/2016/05/27/using-testng-framework-with-tycho/, looks like you already did something, would you mind create a PR for it?
otherwise, I can do it later, just let me know.
thanks

**Comment by missedone** [comment]
also, I prefer to create separate OSGi bundle for testng, jcommander, bsh, etc. respectively, rather then embedded into all into testng bundle.

**Comment by mschreiber** [comment]
Hi Nick,


I created another OSGi Bundle that includes testng, bsh and jcommander in
one bundle. I can try to create a PR for it but as you said, it might be a
good idea to separate the jars into one OSGi bundle per jar remove the jars
form the eclipse-plugin and add the created OSGi bundles as dependencies to
it.

-martin


2016-09-25 7:39 GMT+02:00 Nick Tan <notifications@github.com>:

**Comment by mschreiber** [comment]
I tried to craete a PR for it but found out that it might be sufficient if the build of the testNG library does provide the Eclipse Update Site. Currently the gradle script for the testNG library does already create the OGSi Bundle Information into the MANIFEST file. With the gradle plugin https://plugins.gradle.org/plugin/org.standardout.bnd-platform it is possible to create Eclipse Update sites. 

So this issue might be moved to testNG?

**Comment by missedone** [comment]
hi @mschreiber 
I prefer to manage them in a separate project, just created one: https://github.com/testng-team/testng-p2

you can organize the OSGi bundles of TestNG, jcommander, bsh, etc. there.

once the repo is down, we need to figure out way to make it be available for Tycho so that we can build TestNG Eclipse Plugin without any issue.
and definitely, we also need to update plugin to depends on the OSGi bundles instead of embedded jars.

**Comment by cbeust** [comment]
You probably mean "done" and not "down" ;-)


-- 
Cédric
