### ISSUE TITLE
Missing failed assert details in the console

### ISSUE THREAD

**Issue by ahoehma** [cbeust/testng-eclipse#288]
### Expected behaviour
Maybe I'm wrong but in the past I guess there was a output of the failed assert on the console ...

### Actual behaviour
Currently I only see the "problem" in the testng view but there its hard to copy something, or sometimes I can't see the full error message etc.

### Steps to reproduce
1.  start a test which should fail

### Running Configuration
* Plugin Version:  TestNG	6.9.13.201608191503
* (Optional) Plugin Git Revision: 
  (Since 6.9.11, you can get the plugin git revision via navigating "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")
-- listing properties --
git.commit.id=57419c4c1dea3ed257bb1066b7f95bfb1ee9c382
git.branch=57419c4c1dea3ed257bb1066b7f95bfb1ee9c382
git.build.version=6.9.13-SNAPSHOT
* (Optional) Operating System:  Windows 10

![image](https://cloud.githubusercontent.com/assets/548214/18955147/61828dce-8656-11e6-9296-c866b9c68ab3.png)

**Comment by missedone** [comment]
the workaround is to set the log level to 2 on launchConfiguration tab.
or, you can update to the latest beta, and remove the existing TestNG launch configuration.

**Comment by missedone** [comment]
it's now in the 6.9.13.201609291640 release

**Comment by ahoehma** [comment]
Works. Thank you very much! :+1:
