### ISSUE TITLE
Dependency-Methods seems to be ignored when launching a test suite from a file

### ISSUE THREAD

**Issue by arnaud-g** [cbeust/testng-eclipse#29]
When I launch a test-suite from an XML file, it ignores the dependency-methods annotations.
When I run the tests by a right-click on the class, it works.

It worked with 6.1.1.20110728_1012
It doesn't work anymore with 6.2.0.20110826_0903

**Comment by nukalab** [comment]
I found the solution to run the single test (Method) from Run configuration which has a "dependsOnMethods" method to run first.
I have tried many ways to add the dependency method but finally this worked out.
Adding the dependency method and then the actual method which is intended to run.

Ex: Dell_SIT_HealthChecks_DB#Open_LinuxSession, Dell_SIT_HealthChecks_DB#F901_TestFlow

Here "Dell_SIT_HealthChecks_DB" is the class containing above 2 methods, where "F901_TestFlow" actual intended method to run depends on "Open_LinuxSession" method.

Hope you will try and let us know if this is working for you as well.
