### ISSUE TITLE
IConfigurationListener was not loaded when running Test in Eclipse Plugin

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#298]
https://groups.google.com/d/msg/testng-users/_SmjHXfR0gE/y5dxKYcrBgAJ

**Comment by jmcgrail** [comment]
I can confirm fixed using testng 6.10, eclipse plugin 6.10.0.201612030230, and eclipse  neon.1a (aka 4.6.1).

thanks!
