### ISSUE TITLE
Site testNG

### ISSUE THREAD

**Issue by jmleal** [cbeust/testng-eclipse#299]
Good afternoon

I try install testNG in my eclipse but , this site http://beust.com/eclipse don´t work.

The response is:

Forbidden

You don't have permission to access /eclipse/ on this server.

Thanks :D

**Comment by missedone** [comment]
hi @jmleal, I just tried that the update site works, so could you try again, or double check if you are behind any firewall?

**Comment by cbeust** [comment]
He's probably trying to access this URL with a browser instead of Eclipse.

-- 
Cédric

**Comment by jmleal** [comment]
Goodmorning

Thamks for your  response, effectively the problem is the proxy of my enterprise.

Thanks one more than

Best regards
