### ISSUE TITLE
support file based test result synchronizer

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#305]
today, TestNG eclipse plugin use socket to communicate the test result from runtime TestNG process to plugin (see more in [testng-remote](http://github.com/testng-team/testng-remote/issues)).
this approach has some drawbacks:
1. requires network, communication via sockets on localhost (127.0.0.1), some bad network configuration would break the communication.
2. testng-remote implements the adaptors are version dependent. some changes in TestNG might require additional adaptors for future TestNG version.

so it probably be better to add file based test result synchronizer rather than socket based, to bypass the above issues.

the idea comes from what IntelliJ does, that IntelliJ simply print the markable line to console (stdout), and there's a watcher interprets the marks and update the test status on the GUI view.

for TestNG eclipse plugin, we can facilitate with a file based watcher, polling the test result and update it to TestNG result viewer.
below are things to be done to achieve this:
* [ ] define the file format, though there's already `testng-results.xml`, but need to understand how the content being flushed (at realtime of each result, vs. one time after complete), and looks like paring xml stream is sort of hard than a plain text line (probably delimiter based, or json based, etc.)
* [ ] probably need implement a new listener to write the file result in new format
* [ ] implement the watcher to tail/polling the result file, and update the GUI viewer.

@cbeust , @juherr, please weigh in your idea, thanks

**Comment by cbeust** [comment]
I'm confused: are you using a file or stdout to pass these results?

Either way, this seems like a step back compared to the socket approach, and I'm not really convinced the drawbacks you list are that much of an issue: the current approach seems to work fine and it's pretty easy to evolve it too...

**Comment by missedone** [comment]
I was saying a file based communication.

I'm OK if you don't think it worth a go.

BTW, I noticed there's code watcher test-result.xml, but looks like this function is incomplete?
