### ISSUE TITLE
TestNG Tests continue forever (but not always)

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#308]
From: http://stackoverflow.com/q/41739414/4234729

### Plugin Version
6.10.0.201612030230

### Actual behaviour
> My TestNG tests are weird... sometimes they finish, but sometimes they don't, even though there is nothing random.
> 
> Most of the tests run, then nothing happens, except the TestNG result bar is green, and flickering every few seconds (as if something would happen in the background)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
closing this, looks like the SO marked answered.
