### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#309]
"peer not authenticated" from http://stackoverflow.com/q/41847549/4234729
"validator exception" from http://stackoverflow.com/q/41822369/4234729

**Comment by missedone** [comment]
Oops, just realize several people on SO encounter the similar installation issue, very much looks like being caused by SSL, and I think this [answer](http://stackoverflow.com/a/41848751/4867232) should work, will try to simulate the issue and write down a wiki page for this.

**Comment by juherr** [comment]
Yes, it's just strange it only happens now.

**Comment by juherr** [comment]
Fyi, a new similar issue here: http://stackoverflow.com/q/41976583/4234729

**Comment by cbeust** [comment]
Which links to this similar issue:  http://stackoverflow.com/questions/41847549/not-able-to-install-testng-in-eclipse-kepler

It's preoccupying that the timing seems to match when I installed the redirection requested by @missedone.

Nick, any idea what's causing this issue? Should I roll back the redirect?

**Comment by juherr** [comment]
> Which links to this similar issue

Sure, I made it! ;)

> any idea what's causing this issue?

Could it be the http to https redirection?

**Comment by missedone** [comment]
Yep, I believe it's caused by the redirection onto release update site, however not all people encounter this issue, will try to seek a solution doable at our side, rather at each user side.
Will try to remove some CA certificate to break the certificate chain, trying to reproduce at my local first.

**Comment by missedone** [comment]
hi @cbeust , I think we need to revert the redirection http://beust.com/eclipse.
when doing this, you need to manually deploy the update site to beust.com:
1. download update site archive: https://dl.bintray.com/testng-team/testng-eclipse-release/zipped/6.10.0.201612030230/site_assembly.zip
2. unzip it to the dir where you originally host the update sites.

in future, we can keep deploying the update site to Bintray as it is today, and figure out a way to sync it to beust.com
what do you think?

**Comment by juherr** [comment]
And what if the redirection use `http://dl.bintray.com/...` instead of `https://dl.bintray.com/...`?
Then, no more certificate in the loop.

**Comment by missedone** [comment]
hi @juherr, good catch, looks like the http URL is working: `curl -i http://dl.bintray.com/testng-team/testng-eclipse-release/`.
I thought it's https only.
@cbeust , could you have a try, thanks

**Comment by cbeust** [comment]
Works for me:

```
~/t$  curl -i http://dl.bintray.com/testng-team/testng-eclipse-release/.
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 02 Feb 2017 19:40:49 GMT
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive

<html>
<head>
<script>
//1486064448854
function navi(e){
	location.href = e.target.href.replace('/:','/'); e.preventDefault();
}
</script>
```

**Comment by cbeust** [comment]
@missedone Concretely, what do you want me to do?

**Comment by missedone** [comment]
Hi @cbeust, could you update the redirection to use http URL rather than https, both for release and beta updatesite. Thx.

**Comment by cbeust** [comment]
@missedone Done. FYI, here is the current `.htaccess`:

```
Redirect 301 /eclipse http://dl.bintray.com/testng-team/testng-eclipse-release/
Redirect 301 /eclipse-beta http://dl.bintray.com/testng-team/testng-eclipse/
```

**Comment by missedone** [comment]
the new redirection works. thanks
