### ISSUE TITLE
Problems downloading artifact: org.eclipse.update.feature,org.testng.eclipse

### ISSUE THREAD

**Issue by wanix1988** [cbeust/testng-eclipse#316]
### Eclipse Version
Eclipse Java EE IDE for Web Developers.
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200

### Plugin Version
    TestNG	6.10.0.201612030230
    TestNG M2E Integration (Optional)	6.10.0.201612030230

### Expected behaviour
can install testng eclipse plugin successfully

### Actual behaviour
cannot install testng eclipse plugin

### Any relate message in "Error Log" view
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: org.eclipse.update.feature,org.testng.eclipse,6.10.0.201612030230.
MD5 hash is not as expected. Expected: fc03888b67f7f8df10e99e60c3de7cd8 and found 7406f759ddeb121ee8de567e84a060a6.

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [x] Linux
- [ ] OSX

**Comment by missedone** [comment]
hi @wanix1988, could it be a temporary network issue? 
I just installed and things work fine.
or, could you double check is there any firewall or proxy setting could impact the download?
thx.

**Comment by missedone** [comment]
or, as a workaround, download the offline update-site to your local, then install the plugin from archive.

closing this ticket now, feel free to reopen if still have issue.

**Comment by juherr** [comment]
@missedone Similar issue on SO http://stackoverflow.com/q/43693776/4234729
