### ISSUE TITLE
Not able to install testNG to eclipse neon

### ISSUE THREAD

**Issue by santhu11** [cbeust/testng-eclipse#317]
Version: Neon.3 Release (4.6.3RC2)
Build id: 20170223-1031

> 'Eclipse -> About Eclipse -> Installation Details -> Locate the TestNG plugin'

> Or, optional, provide the git revision of plugin: "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")

testNG is not installing on to my IDE. It's throwing an error.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [1] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
could you paste the error msg (or screenshot) here?

**Comment by innocentliny** [comment]
FYI.
![image](https://cloud.githubusercontent.com/assets/5312376/23904565/44f13e28-0903-11e7-8847-16328ea652a3.png)
![image](https://cloud.githubusercontent.com/assets/5312376/23904578/51506130-0903-11e7-8d0e-68375a4b65e4.png)

**Comment by missedone** [comment]
The URL is incorrect.
Please remove colon ":" after slash "/".
See https://github.com/cbeust/testng-eclipse/blob/master/README.md#update-sites

**Comment by innocentliny** [comment]
Hi, missdone:

Manual remove ":" is not working.
Colon ":" is added automatically to all web links by dl.bintray.com
And I can't install TestNG via marketplace, too.

![image](https://cloud.githubusercontent.com/assets/5312376/23934485/a6bd6dfc-0980-11e7-8fa3-7f012ba7d67e.png)

**Comment by missedone** [comment]
could you install from this version specific url? https://dl.bintray.com/testng-team/testng-eclipse-release/6.11.0/

**Comment by innocentliny** [comment]
Hi, missedone,

I can install from https://dl.bintray.com/testng-team/testng-eclipse-release/6.11.0/.
Thank you.

**Comment by missedone** [comment]
good to know ;)

**Comment by santhu11** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; } Okay I will look in to it and download
Thank u


Sent from Yahoo Mail for iPhone


On Wednesday, March 15, 2017, 6:26 PM, Nick Tan <notifications@github.com> wrote:


good to know ;)
