### ISSUE TITLE
Unable to add TestNG for ubuntu 16.04

### ISSUE THREAD

**Issue by G-911106L** [cbeust/testng-eclipse#321]
Operating System - Ubuntu(16.04)
Eclipse version - 3.8
Java version    - 1.8.0

**I couldn't proceed adding TestNG file - It is showing below error message**

Cannot complete the install because one or more required items could not be fg und.
  Software being installed: TestNG M2E Integration (Optional) 6.11.0.201703011520 (org.testng.eclipse.maven.feature.feature.group 6.11.0.201703011520)
  Missing requirement: TestNG M2E Integration 6.11.0.201703011520 (org.testng.eclipse.maven 6.11.0.201703011520) requires 'bundle org.eclipse.m2e.core 1.5.0' but it could not be found
  Cannot satisfy dependency:
    From: TestNG M2E Integration (Optional) 6.11.0.201703011520 (org.testng.eclipse.maven.feature.feature.group 6.11.0.201703011520)
    To: org.testng.eclipse.maven [6.11.0.201703011520]

![screenshot from 2017-03-14 14-21-59](https://cloud.githubusercontent.com/assets/19836776/23892684/9d164b94-08c1-11e7-9498-2fc20793ae3e.png)

**Comment by missedone** [comment]
wow, you're using the classic version 3.8 👍 
could you update to newer version, e.g. the latest release version Neon.

the error message indicates that there's missing M2E plugin in your Eclipse, so if you want to stick on 3.8, could you try not install the optional TestNG M2E Integration plugin? or, you need to have M2E 1.5 or above installed first.

**Comment by GeetL** [comment]
Thank You.. This issue is solved.
