### ISSUE TITLE
2nd call to same test method in testng.xml ignored

### ISSUE THREAD

**Issue by Brokeneggs** [cbeust/testng-eclipse#323]
It seems that testng won't allow to run the same method or class in one test execution multiple times .For example, the last test below which is a second run of the clickBrowserTab1 @Test-annotated method is completely ignored.  After Tab2 clicked, i need to rerun clickBrowserTab1. I understand that, as a workaround, I could have two differently-named @Test methods which each call the method to click Tab1, but that is ugly. 

```
<test name="CommonReportingTests" preserve-order="true" > 
    <classes> 
        <class name="jason.test.Main"> 
                       <methods> 
                            <include name="clickBrowserTab1" /> 
                            <include name="clickBrowserTab2" /> 
                            <include name="clickBrowserTab1" / > 
                     </methods> 
       </class>
    </classes>
</test>
```

**Comment by missedone** [comment]
Closing this. Track https://github.com/cbeust/testng/issues/1395 instead
