### ISSUE TITLE
Firefox starts, but does not open the URL

### ISSUE THREAD

**Issue by GeetL** [cbeust/testng-eclipse#324]
### Plugin Version
Eclipse Version - Neon.3 64-bit
Mozilla Firefox - 44.02 version
Java - 1.8.0
Selenium - 3.3.1
OS - Window 7(64-bit)
Latest gecko driver for Firefox is downloaded and path is given in the script

 I am unable to open the url, Just Firefox window opens when I run the program with below error message

Apr 06, 2017 5:08:03 PM org.openqa.selenium.remote.ProtocolHandshake createSession
INFO: Detected dialect: OSS
PASSED: LoginFuction(Method name)

**Comment by missedone** [comment]
what if you run the test on command line? for example, by using Maven or Gradle, etc.

**Comment by GeetL** [comment]
I am beginner in Selenium & Maven/Gradle idea is not there.

**Comment by missedone** [comment]
could you post the question on stackoverflow, there might be more people can help you out

**Comment by GeetL** [comment]
Thank You.. I solved it.
