### ISSUE TITLE
Misleading installation error when beust.com/eclipse is down

### ISSUE THREAD

**Issue by CSRessel** [cbeust/testng-eclipse#333]
### Plugin Version
6.11.0.201703011520

### Expected behaviour
N/A

### Actual behaviour
beust.com/eclipse appeared to be down this morning sometime around 11am eastern, and when attempting to install the TestNG plugin at this time Eclipse pops up a dialog box saying "Login required," asking for "login details for beust.com," and after attempting to continue the installation without providing login details, the final error is "No artifact repository available."

Installation proceeded fine approximately an hour later, when that url appeared to be back up.

### Any relate message in "Error Log" view
At the time I didn't think to copy the error, my apologies.

### The Dependency Management tool for your project
N/A

### Operating System

- [ ] Windows
- [ ] Linux
- [X] OSX

**Comment by missedone** [comment]
closing as duplicate with #334
