### ISSUE TITLE
if m2e integration is installed, reportNG listener with spaces in title breaks testNG

### ISSUE THREAD

**Issue by borisivan** [cbeust/testng-eclipse#336]
### Plugin Version
> 'Eclipse -> About Eclipse -> Installation Details -> Locate the TestNG plugin'
  TestNG	6.11.0.201703011520	org.testng.eclipse.feature.group	Cedric Beust
  TestNG M2E Integration (Optional)	6.11.0.201703011520	org.testng.eclipse.maven.feature.feature.group	TestNG Team

> Or, optional, provide the git revision of plugin: "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")

### Expected behaviour
When I right click on a @Test method, or suite file, that I can Run As -> testNG test, and have it execute.

### Actual behaviour
The option Run As -> testNG test is there, but I always receive:

Error: Could not find or load main class WORD2

(where WORD2) is a word as shown below (obfuscating company data for the bug report). There is no other place in pom.xml where WORD2 resides.

            <execution>
              <id>default-test</id>
              <phase>integration-test</phase>
              <goals>
                <goal>test</goal>
              </goals>
              <configuration>
                <testFailureIgnore>true</testFailureIgnore>
                <reportsDirectory>obfuscated</reportsDirectory>
                <skip>false</skip>
                <maven.test.failure.ignore>true</maven.test.failure.ignore>
                <properties>
                  <property>
                    <name>usedefaultlisteners</name>
                    <value>false</value>
                  </property>
                  <property>
                    <name>listener</name>
                    <value>org.testng.reporters.XMLReporter,org.uncommons.reportng.HTMLReporter,org.uncommons.reportng.JUnitXMLReporter</value>
                  </property>
                </properties>
                <systemPropertyVariables>
                  <org.uncommons.reportng.title>WORD1 WORD2 WORD3 WORD4</org.uncommons.reportng.title>
                  <org.uncommons.reportng.frames>false</org.uncommons.reportng.frames>
                </systemPropertyVariables>
                <testClassesDirectory>obfuscated</testClassesDirectory>
                <suiteXmlFiles>
                  <suiteXmlFile>src/main/testSuites/suiteFileName.xml</suiteXmlFile>
                </suiteXmlFiles>
                <testSourceDirectory>obfuscated</testSourceDirectory>
              </configuration>
            </execution>

If I place the reportNG listener title in quotes:

                  <org.uncommons.reportng.title>"WORD1 WORD2 WORD3 WORD4"</org.uncommons.reportng.title>

... everything works fine.

Without the m2e plugin, everything works fine regardless if the reportNG title has spaces or not.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@borisivan, fixed, pls verify with the latest beta: http://beust.com/eclipse-beta.
