### ISSUE TITLE
Error occured while installing testng plugin in Eclipse neon

### ISSUE THREAD

**Issue by gelluru** [cbeust/testng-eclipse#339]
![testng_error](https://user-images.githubusercontent.com/18165980/27064498-575c9f0e-5015-11e7-841e-672079f15539.jpg)
### Plugin Version
> 'Eclipse -> About Eclipse -> Installation Details -> Locate the TestNG plugin'

> Or, optional, provide the git revision of plugin: "About Eclipse -> 'Installation Details' at left bottom -> 'Configuration' tab -> scroll down to '*** TestNG for Eclipse Details:' portion ")

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
could you try with this update site url: `http://dl.bintray.com/testng-team/testng-eclipse-release/`

**Comment by josh-berg** [comment]
I am getting the same problem.  Also tried with with the bintray url and got the same error.

**Comment by missedone** [comment]
pls refer #341 that people can install from `http://dl.bintray.com/testng-team/testng-eclipse-release/`

see also the troubleshooting page: https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md

**Comment by missedone** [comment]
close as no response, feel free to re-open it if you still have the issue.

**Comment by dinkleavi** [comment]
In eclipse oxygen while installing TestNG i am getting this error  [http://prntscr.com/iiudd5]
please help me out
windows 8 64 bit

**Comment by missedone** [comment]
@dinkleavi, you can download the zipped update site for offline installation, see details: https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md

**Comment by dinkleavi** [comment]
@missedone   can u please tell  me 
where should i  exactly copy the all  offline downloaded file?
i have downloaded this files
![screenshot_1](https://user-images.githubusercontent.com/36773147/36777213-875f11a8-1c1d-11e8-930b-0ace7775e84b.png)

**Comment by missedone** [comment]
@dinkleavi , 
1) put the downloaded zip on your local filesystem your user has access (no need to extract the file).
2) in Eclipse, click "Help -> Install New Software... -> click "Add ..." button -> click "Archive ..." button to browse the zip file", then select the plugins to install.

**Comment by harshal7272** [comment]
![testng problem](https://user-images.githubusercontent.com/116079985/199193554-9bad997b-e1f6-48ad-aec9-9c55c08dd7a1.png)

**Comment by harshal7272** [comment]
how to solve it?
