### ISSUE TITLE
The dependonMethod is not work when i dependon a different class method，this issue seems have been fixed in 6.9.9，but now i still have this problem

### ISSUE THREAD

**Issue by z475546259** [cbeust/testng-eclipse#344]
My eclipse is v4.5
eclipse-testNg 6.11
testNg jar 6.9.10
org.testng.TestNGException: 
com.zhubajie.autotest.announcementservice.TestUpdateAnnouncement.testCase() is depending on method public void com.zhubajie.autotest.announcementservice.TestSaveAnnouncement.testCase(java.util.Map,java.lang.Object), ## **which is not annotated with @Test or not included.**
	at org.testng.internal.MethodHelper.findDependedUponMethods(MethodHelper.java:112)
	at org.testng.internal.MethodHelper.topologicalSort(MethodHelper.java:211)
	at org.testng.internal.MethodHelper.sortMethods(MethodHelper.java:287)
	at org.testng.internal.MethodHelper.collectAndOrderMethods(MethodHelper.java:60)
	at org.testng.TestRunner.initMethods(TestRunner.java:496)
	at org.testng.TestRunner.init(TestRunner.java:247)

**Comment by missedone** [comment]
if you run manen test, will `TestSaveAnnouncement.testCase` be executed first?
for example: `mvn -Dtest=TestSaveAnnouncement,TestUpdateAnnouncement test`

**Comment by z475546259** [comment]
No，i am run as testng
![image](https://user-images.githubusercontent.com/22720687/28510104-eaa43dd4-7078-11e7-8555-98613a1dd0c0.png)

**Comment by missedone** [comment]
@z475546259 , pls review the test case in PR #345 reflects your case. thx

**Comment by missedone** [comment]
you can verify with latest snapshot from beta update site: `http://beust.com/eclipse-beta`

**Comment by missedone** [comment]
remember to remove the old launch configuration before run the test.
