### ISSUE TITLE
TestNG error when executing script in selenium ide

### ISSUE THREAD

**Issue by missedone** [cbeust/testng-eclipse#355]
https://stackoverflow.com/questions/46194454/testng-error-when-executing-script-in-selenium-ide

**Comment by ajaydroliya** [comment]
[WNS.zip](https://github.com/cbeust/testng-eclipse/files/1301706/WNS.zip)

**Comment by ajaydroliya** [comment]
[Detail.zip](https://github.com/cbeust/testng-eclipse/files/1301707/Detail.zip)

**Comment by missedone** [comment]
@ajaydroliya , sorry for late response.
I just took a look at your .classpath:
```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
	<classpathentry kind="src" path="src"/>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8"/>
	<classpathentry kind="lib" path="D:/Softwares/selenium-java-3.4.0/lib/cglib-nodep-3.2.4.jar"/>
...
	<classpathentry kind="lib" path="D:/Softwares/selenium-java-3.4.0/client-combined-3.4.0-nodeps.jar"/>
<!-- Nick: you need to remove this entry: testng-6.0.jar, it's recommended to use TESTNG_CONTAINER  -->
	<classpathentry kind="lib" path="C:/Users/orange/Downloads/testng-6.0.jar"/>
	<classpathentry kind="lib" path="C:/Users/orange/Downloads/CSV Pack/opencsv-3.2.jar"/>
	<classpathentry kind="con" path="org.testng.TESTNG_CONTAINER"/>
	<classpathentry kind="output" path="bin"/>
</classpath>
```

**Comment by hellobk123** [comment]
@missedone  Facing the same  error ..  Pls help me
![image](https://user-images.githubusercontent.com/32698421/91028317-ef817b80-e61a-11ea-8bef-8433c0848734.png)

**Comment by hellobk123** [comment]
[Framework22.zip](https://github.com/cbeust/testng-eclipse/files/5116997/Framework22.zip)

Attached ZIp file

**Comment by missedone** [comment]
@hellobk123 , could you double check there's on old testng in "Referenced Libraries"
i see you have testng 7.0.0 in pom.xml, that's great, and make pls sure use only maven to manage your project dependencies, rather than IDE specific like "Reference Libraries"
