### ISSUE TITLE
Surefire 2.17 late replacement: Error: Could not find or load main class @{argLine}

### ISSUE THREAD

**Issue by kay** [cbeust/testng-eclipse#357]
### Problem Statement

From http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#argLine
> Since the Version 2.17 using an alternate syntax for argLine, @{...} allows late replacement of properties when the plugin is executed, so properties that have been modified by other plugins will be picked up correctly. See the Frequently Asked Questions page with more details:
> http://maven.apache.org/surefire/maven-surefire-plugin/faq.html 

However TestNG-eclipse does not seem to handle use of the late replacement operator @ yet. 

I believe this is the key method and line: https://github.com/cbeust/testng-eclipse/blob/7600b768fee086ea1d89993f47d41c4b6bac91cb/testng-maven-eclipse-plugin/src/org/testng/eclipse/maven/MavenTestNGLaunchConfigurationProvider.java#L293

The result is running any TestNG test in Eclipse with these surefire settings result in the following being printed to stderr

> Error: Could not find or load main class @{argLine}

Workaround: Do not use late replacement or disable the argLine option under preferences > testng > maven

### Any relate message in "Error Log" view
None

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [x] OSX

Untested on other platforms but should affect those too.

**Comment by missedone** [comment]
@kay , I can make MavenTestNGLaunchConfigurationProvider treat `@{...}` as `${...}`, that's saying  `@{...}` will also use the init properties value.
the reason is, MavenTestNGLaunchConfigurationProvider does not execute any maven plugin/goal before launching the tests, it simply parse the effective pom xml file, extract the argLine then append to runtime TestNG process.
are you OK with this?

**Comment by kay** [comment]
Understood, and that sounds like a good solution. Truthfully I had intended to raise this first for you to review & then raise a PR myself with the exact same solution but ran out of time this weekend.

**Comment by missedone** [comment]
@kay , pls go ahead to raise a PR once you have a chance, let me know what I can assist.
thx

**Comment by missedone** [comment]
@kay, I just made a quick fix for it.
you can test with latest beta: http://dl.bintray.com/testng-team/testng-eclipse/updatesites/6.12.0.201710150444/

**Comment by kay** [comment]
Thanks @missedone looks good, sorry I didn't get around to this. Great turnaround, bravo.
