### ISSUE TITLE
Icons looks pixelated on HiDPI monitors

### ISSUE THREAD

**Issue by davidbilge** [cbeust/testng-eclipse#363]
### Problem Statement
Basically all icons in the TestNG view look pixelated on HiDPI displays. Note that many other icons in Eclipse look nice and crisp on my display.

![image](https://user-images.githubusercontent.com/762988/31703733-3e8723d2-b3de-11e7-8e8b-282292a170fb.png)
(you need to click on the screenshot to see it in full resolution)

### Any relate message in "Error Log" view
(Not relevant)

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@davidbilge , deployed to the beta channel, pls have a try: http://dl.bintray.com/testng-team/testng-eclipse/updatesites/6.12.0.201710180907/

**Comment by davidbilge** [comment]
That was quick. Looks a lot better, although the TestNG icon itself is still pixelated:

![image](https://user-images.githubusercontent.com/762988/31719618-564f2d76-b414-11e7-8c31-51b5abebb98e.png)

**Comment by missedone** [comment]
right, for TestNG icon itself, I need help, @cbeust , could you provide hidpi icons for TestNG icons?

**Comment by missedone** [comment]
the icons here are all need "@2x" (aka, hidpi) version: https://github.com/cbeust/testng-eclipse/tree/master/testng-eclipse-plugin/icons/full/main16
