### ISSUE TITLE
Unable to install testNG in Eclipse Oxygen

### ISSUE THREAD

**Issue by Mohammedf2017** [cbeust/testng-eclipse#368]
Eclipse IDE for Java Developers
Version: Oxygen Release (4.7.0)
Build id: 20170620-1800
OS: Windows 10, v.10.0, x86_64 / win32

Steps 
1. Open eclipse oxygen in windows OS
2. Go to help - > Install new software 
3.Click on Add and  Enter http://beust.com/eclipse in location
4. Enter TestNG in name and click ok
5. it says "could not find http://beust.com/eclipse."

**Comment by missedone** [comment]
@Mohammedf2017, please read troubleshooting doc see if it can help you.
https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md
