### ISSUE TITLE
Parallel test execution not working with latest TestNG 6.13

### ISSUE THREAD

**Issue by sanojqa** [cbeust/testng-eclipse#371]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@sanojqa, please add more detail about the problem statement, or share a sample project to reproduce.

/CC @juherr, are you aware of any relate known issue at your radar?

**Comment by sanojqa** [comment]
@missedone I am used 6.12 version of TestNG for execution of my automated test cases and was able to run two tests parallel mode. I migrated to eclipse oxygen and installed the latest TestNG 6.13 version, unfortunately there I cannot able to run my two tests in parallel mode even I mentioned parallel="tests" in testng.xml file. Have any different implementation done in the new version of TestNG?

**Comment by missedone** [comment]
@sanojqa , is the issue similar as https://github.com/cbeust/testng/issues/1636 ?

**Comment by juherr** [comment]
@missedone I think you found the root issue :)

**Comment by missedone** [comment]
@sanojqa , please verify the fix in the beta build:
https://dl.bintray.com/testng-team/testng-eclipse/updatesites/6.14.0.201712271209/

please add comments here https://github.com/cbeust/testng/issues/1636 if you still have the issue
