### ISSUE TITLE
Support for surefire and failsafe <properties> tag

### ISSUE THREAD

**Issue by gayanper** [cbeust/testng-eclipse#373]
### Problem Statement
When defining system properties under <properties> tags are not picked up by TestNG M2E plugin. From the surefire and failsafe documentations the <properties> is the recommended option to configure system properties for TestNG.

ex: Documentation for <properties> in failsafe plugins
> List of properties for configuring all TestNG related 
    configurations. This is the new preferred method of configuring 
    TestNG.

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@gayanper, could you share the sample usage of 'properties' of surefire/failsafe configuration

**Comment by missedone** [comment]
Nevermind, I see the examples here: http://maven.apache.org/surefire/maven-surefire-plugin/examples/testng.html

just learn a new way to pass the testng arguments with surefire/failsafe `<configuration><properties>` tags.

**Comment by missedone** [comment]
@gayanper , you can verify the new feature in the beta build: https://dl.bintray.com/testng-team/testng-eclipse/updatesites/6.14.0.201712270620/
