### ISSUE TITLE
TestNG Run As fails to resolve parent poms with maven project

### ISSUE THREAD

**Issue by xavipen** [cbeust/testng-eclipse#377]
### Problem Statement
I have a pom with defines a parent pom. Let's call the parent pom level3 artifact.

level3 artifact has also defined a parent pom. Let's call this parent pom level2 artifact.

level2 artifact has also defined a parent pom. Let's call this parent pom level1 artifact.

I have writen a simple test. However when i try to Run As the test eclipse replies with missing artifact level2 and the test does not start.

The maven configuration is fine. I can perform a maven clean install without issues.

For test I made the project pom to use level2 as the parent pom. When i did this then the error evolved and complain about level1 artifact missing.

It seems that there is an issue with projects with multiple parent poms.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

plugin: org.eclipse.m2e.core
Could not resolve artifact esa.egscc:esa.egscc.parentPom:pom:0.10.5-v201702141244

### The Dependency Management tool for your project

- [x ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x ] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
sounds like something wrong with the m2e (maven eclipse plugin), could you try following steps:
1. right click on your projects, Maven -> update project..., this way to sync the maven settings in eclipse
2. click "Project" on top level menu, select "Clean..." to rebuild the projects.

then, you can check is there any problem on the projects.

**Comment by missedone** [comment]
should be same issue as #383 .

@xavipen, could verify with the latest beta: https://dl.bintray.com/testng-team/testng-eclipse/updatesites/6.14.0.201802150932/
