### ISSUE TITLE
How to create test-output folder ??

### ISSUE THREAD

**Issue by viteshk92** [cbeust/testng-eclipse#382]
### Problem Statement
**Unable to create test-output folder
How to create path for the test-output??
Even though i have refreshed it many times.
Using Eclipse Version: Oxygen.2 Release (4.7.2)**

### Any relate message in "Error Log" view

![image](https://user-images.githubusercontent.com/35993751/35699072-f70196d4-07b4-11e8-91b0-3dd89ba12afd.png)

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows 10

**Comment by missedone** [comment]
You can unchecked the option "absolute output path", then remove the leading slash of the output path "/target/test-output"

**Comment by missedone** [comment]
Then it creates the output dir under your project folder, otherwise it's absolute path on your system.

Btw, "target" is the default output dir of maven, it's hidden on package explore view in eclipse by default.

**Comment by viteshk92** [comment]
Hey, i did what you told and after refresh there's no test-output folder.
See the below screenshot.

![image](https://user-images.githubusercontent.com/35993751/35722076-decd65c8-081a-11e8-9ad0-9c24e31a299f.png)

**Comment by viteshk92** [comment]
One more thing can you check the my Preference for the TestNG in the below screenshot.
If there's anything to check/uncheck, kindly let me know.

![image](https://user-images.githubusercontent.com/35993751/35722203-5faa398c-081b-11e8-80d1-cea58eccdc09.png)

**Comment by missedone** [comment]
the ouput dir should be `test-output` rather than `/test_output` (remove the leading slash)

**Comment by viteshk92** [comment]
removed leading slash and after removing slash i refreshed the package explorer but still no luck..

**Comment by viteshk92** [comment]
i got the test-output.. You cab close the issue now..

**Comment by missedone** [comment]
Did you see any error in error log viewer?

**Comment by vasundharabollam** [comment]
we should configure build path
right click on TestNg--.>buildpath..>configure buildpath

**Comment by NagarrajS** [comment]
set the below value in Eclipse > Preference > TestNG Output directory
vale ( ${basedir}/test-output

**Comment by akankshasawase** [comment]
> set the below value in Eclipse > Preference > TestNG Output directory vale ( ${basedir}/test-output

Thank you I got solution from you
