### ISSUE TITLE
Spring boot 2.0.0.M7+RC1 projects not testable in Eclipse Oxygen 2

### ISSUE THREAD

**Issue by vguna** [cbeust/testng-eclipse#383]
I'm using Spring Boot 2.0.0.RC1 (also tried M7) and tried to get the example Hello World project working In Eclipse Oxygen 2:

https://docs.spring.io/spring-boot/docs/current/reference/html/getting-started-first-application.html

Just adapted the version, added Spring snapshot repos and imported into Eclipse.

```
    <repositories>

        <!-- for getting spring milestones+snapshots -->
        <repository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
        <repository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <!-- for getting spring milestones+snapshots -->
    <pluginRepositories>
        <pluginRepository>
            <id>spring-snapshots</id>
            <name>Spring Snapshots</name>
            <url>https://repo.spring.io/snapshot</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </pluginRepository>
        <pluginRepository>
            <id>spring-milestones</id>
            <name>Spring Milestones</name>
            <url>https://repo.spring.io/milestone</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
```

So far no problem. Also running it seems to work. Now I tried to add tests via testng. But executing it via testng plugin fails in Eclipse with:

```
Could not resolve artifact org.springframework.boot:spring-boot-dependencies:pom:2.0.0.RC1
Missing org.springframework.boot:spring-boot-dependencies:pom:2.0.0.RC1
```

My guess would be it has some problems with the `spring-boot-starter-parent` pom's `<relativePath>../../spring-boot-dependencies</relativePath>` to the `spring-boot-dependencies`.

**Nevertheless, the same works if I just switch over to JUnit `@Test`. It also works with testng using maven on cmdline. Only executing the testcase via testng Eclipse plugin seems to be a problem.**

### Any relate message in "Error Log" view
```
eclipse.buildId=4.7.2.M20171130-0510
java.version=1.8.0_112-ea
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -clean

org.eclipse.m2e.core
Error
Fri Feb 02 12:09:41 CET 2018
Could not resolve artifact org.springframework.boot:spring-boot-dependencies:pom:2.0.0.RC1
```

### The Dependency Management tool for your project
- [x] Maven
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

With or without TestNG Library in Buildpath makes no difference.

### Operating System
- [x] OSX

**Comment by vguna** [comment]
I just uninstalled the optional "TestNG m2e integration" and now it seems to work.
I'm wondering though what I'm looing now.

**Comment by missedone** [comment]
@vguna, I guess I know the cause, will try to reproduce and fix it.

**Comment by vguna** [comment]
Sounds promising. Thanks for taking a look :)!

**Comment by missedone** [comment]
@vguna , could you verify with the latest beta: https://dl.bintray.com/testng-team/testng-eclipse/updatesites/6.14.0.201802150932/

**Comment by vgcookies** [comment]
Seems to work. Thanks for the quick fix!
