### ISSUE TITLE
About TestNG  launching problem

### ISSUE THREAD

**Issue by LittleFreshMeet** [cbeust/testng-eclipse#384]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
    This is an auto test case. When I run , it should have a running order: Initiate TestNG resources, then go into TestNG process, finally launch code based on TestNG. 
    But I suddenly just hold on the first one, that do not show further log except "TestNG Result Listening Job", after It was launched many times sucessfully. I posted the picture with issue. And I hope it can show log or result in the Console part.
    Could you give me any advice? Thanks a lot.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
![26f80e6e4fd70743b88db776be0795d](https://user-images.githubusercontent.com/36073880/35791401-ae512adc-0a82-11e8-9a34-54e5365a73e1.png)

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Linux

**Comment by missedone** [comment]
duplicates with #352
