### ISSUE TITLE
Wrong MD5 problem when install testng-eclipse from updatesite

### ISSUE THREAD

**Issue by nkjackzhang** [cbeust/testng-eclipse#390]
### Problem Statement
When i downloaded offline zip from url `http://dl.bintray.com/testng-team/testng-eclipse-release/zipped/6.14.0.201802161500/:org.testng.eclipse.updatesite.zip` on updatesite `http://dl.bintray.com/testng-team/testng-eclipse-release/zipped/`, i found that it's actually `6.12.0.201709050550`.
The rigth download url is `https://dl.bintray.com/testng-team/testng-eclipse-release/zipped/6.14.0.201802161500/org.testng.eclipse.updatesite.zip` which does't contain `":"`, i don't know why the `":"` makes so big diffence.

### Any relate message in "Error Log" view
no error log.

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
duplicates with #391 , please either use the download links from https://github.com/cbeust/testng-eclipse#update-sites, or remove the ":" manually.
the thing is, when you browse the bintray link in your web browser, if you right click and copy the link, you will get the colon, however, if you just click on the link, you won't get the issue. maybe the ":" is generated by Bintray on purpose.

**Comment by nkjackzhang** [comment]
I'm sorry, because some mistake, the content is duplicate with issues-390, i will edit the content.

**Comment by missedone** [comment]
y, probably as you stated that caused by http vs. https.
