### ISSUE TITLE
Wrong testng-eclipse version on offline updatesite

### ISSUE THREAD

**Issue by nkjackzhang** [cbeust/testng-eclipse#391]
### Problem Statement
When i downloaded offline zip from url `http://dl.bintray.com/testng-team/testng-eclipse-release/zipped/6.14.0.201802161500/:org.testng.eclipse.updatesite.zip` on updatesite `http://dl.bintray.com/testng-team/testng-eclipse-release/zipped/`, i found that it's actually `6.12.0.201709050550`.
The rigth download url is `https://dl.bintray.com/testng-team/testng-eclipse-release/zipped/6.14.0.201802161500/org.testng.eclipse.updatesite.zip` which does't contain `":"`, i don't know why the `":"` makes so big diffence.

### Any relate message in "Error Log" view
no error log.

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
the colon ":" comes from Bintray, that's also why I removed the ":" intentionally in the update site download list: https://github.com/cbeust/testng-eclipse#update-sites.

**Comment by nkjackzhang** [comment]
Maybe I have found the real reason, if you use `https`, even with the colon ":", that's all fine, you will get rigtht version; if you use `http`, even using the url http://dl.bintray.com/testng-team/testng-eclipse-release/zipped/6.14.0.201802161500/org.testng.eclipse.updatesite.zip without the colon ":", you got wrong zip file and wrong version.
The only difference is between `https` and `http`.

**Comment by missedone** [comment]
OK, good to know, thanks
