### ISSUE TITLE
Testng Retryanalyzer

### ISSUE THREAD

**Issue by karthikeyanete** [cbeust/testng-eclipse#394]
### Problem Statement

While running the @Test(retryanalyzer = reanalyzes.class, priority)
is not Working 

@Test is working 

### Any relate message in "Error Log" view
No

### The Dependency Management tool for your project

- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Linux

**Comment by missedone** [comment]
could you share sample project to reproduce the issue? thx

**Comment by missedone** [comment]
for testng usage, pls post question to https://groups.google.com/forum/#!forum/testng-users
for testng bug, pls raise ticket in https://github.com/cbeust/testng
