### ISSUE TITLE
TestNG not showing up in preferences or anywhere in eclipse. 

### ISSUE THREAD

**Issue by Rhythmarora11** [cbeust/testng-eclipse#395]
I downloaded TestNG from eclipse marketplace but still not able to find it out. I see that my eclipse has TestNG in the plugins folder but I still don't see it anywhere. 
Also, there were no error logs while downloading it. What could be the issue?

**Comment by missedone** [comment]
@Rhythmarora11 , pls see if this comment help you: https://github.com/cbeust/testng-eclipse/issues/378#issuecomment-385550524

**Comment by missedone** [comment]
closing as duplicates with #378
