### ISSUE TITLE
Getting an issue while Installing TestNG in Eclipse

### ISSUE THREAD

**Issue by suneelkuppili** [cbeust/testng-eclipse#400]
Getting an issue while Installing TestNG in Eclipse. "Installing Software" pop us shows the below errors
An error occurred while collecting items to be installed
session context was:(profile=epp.package.jee, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Artifact not found: http://beust.com/eclipse/updatesites/6.14.0.201802161500/plugins/org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar.
http://beust.com/eclipse/updatesites/6.14.0.201802161500/plugins/org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar
Artifact not found: http://beust.com/eclipse/updatesites/6.14.0.201802161500/plugins/org.testng_6.14.2.r201802161450.jar.
http://beust.com/eclipse/updatesites/6.14.0.201802161500/plugins/org.testng_6.14.2.r201802161450.jar

The Dependency Management tool for your project
  Maven
  Gradle
  Ant
  Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)
Operating System
Windows 7 - 64 bit
-Same error occurred with Eclipse mars. Eclipse Photon and Eclipse Oxygen

**Comment by missedone** [comment]
pls read troubleshooting first: 
https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md

**Comment by missedone** [comment]
closing this now as no feedback for a long time, feel free to re-open it if the problem remains.
