### ISSUE TITLE
Conflicting Dependencies re TestNG Installation in Eclipse 4.3

### ISSUE THREAD

**Issue by anonRegions** [cbeust/testng-eclipse#402]
### Problem Statement
Trying to install the TestNG plugin in Eclipse Kepler (4.3) I got an error message starting "Cannot complete the install because of a conflicting dependency." I'm given a choice between keeping the installation the same & modifying the items to be installed for compatibility & showing the original error & building my own installation (which I don't know how to do). So it seems my option is the first, but I don't understand the implications of it in re the applications I've already built in Eclipse.'

Please advise. 

Thanks.

### Any relate message in "Error Log" view
See attached log entry. 

### The Dependency Management tool for your project

- [x ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x ] Windows 10
[180831_TestNG_M2E_conflictingDependency.docx](https://github.com/cbeust/testng-eclipse/files/2341518/180831_TestNG_M2E_conflictingDependency.docx)

- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
@anonRegions 

```
From: TestNG M2E (Maven) Integration 6.14.0.201802161500 (org.testng.eclipse.maven 6.14.0.201802161500)
    To: bundle org.eclipse.m2e.core 1.5.0
  Cannot satisfy dependency:
    From: TestNG M2E (Maven) Integration (Optional) 6.14.0.201802161500 (org.testng.eclipse.maven.feature.feature.group 6.14.0.201802161500)
    To: org.testng.eclipse.maven [6.14.0.201802161500]
```

this looks like you don't have M2E (Maven Eclipse Plugin) installed, so you either 
1) install TestNG Eclipse Plugin without the optional plugin "TestNG M2E (Maven) Integration (Optional)"
or, 2) if you do want Maven support, install M2E from market place first.

**Comment by anonRegions** [comment]
OK. Thanks!
