### ISSUE TITLE
Cannot install latest version of TestNG Eclipse Plugin

### ISSUE THREAD

**Issue by mstrahinski** [cbeust/testng-eclipse#406]
Every time when I try to install the latest version of TestNG Eclipse Plugin in my case this is:  6.14.0.201802161500
 
it results in the following error:

"An error occurred while collecting items to be installed
session context was:(profile=epp.package.java, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,org.apache-extras.beanshell.bsh.source,2.0.0.b6.
MD5 hash is not as expected. Expected: 437e2fde4ad799bf47eefb861325b974 and found e08459580c0086b3ec9d10b222268dcf."

The Eclipse versions I've tried with are Eclipse Photon and the latest that I have downloaded today Eclipse SimRel 2018-09 Edition 

### Operating System

- Windows 10

P.S. I've used http://beust.com/eclipse-previous and I have been able to successfully install the plugin, but was unable to succeed with the latest version.

**Comment by manandbytes** [comment]
> MD5 hash is not as expected. Expected: 437e2fde4ad799bf47eefb861325b974 and found e08459580c0086b3ec9d10b222268dcf."

I can not reproduce it, with neither http nor https:

    $ wget http://dl.bintray.com/testng-team/testng-eclipse-release/updatesites/6.14.0.201802161500/plugins/org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar
    $ wget https://dl.bintray.com/testng-team/testng-eclipse-release/updatesites/6.14.0.201802161500/plugins/org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar
    $ md5sum org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar*
    437e2fde4ad799bf47eefb861325b974  org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar
    437e2fde4ad799bf47eefb861325b974  org.apache-extras.beanshell.bsh.source_2.0.0.b6.jar.1

It installs fine:

    osgi> lb -s |grep org.testng
      603|Resolved   |    4|org.testng (6.14.2.r201802161450)|6.14.2.r201802161450
      604|Active     |    4|org.testng.eclipse (6.14.0.201802161500)|6.14.0.201802161500
      606|Starting   |    4|org.testng.eclipse.maven (6.14.0.201802161500)|6.14.0.201802161500
    true
    osgi>

> Every time when I try to install the latest version of TestNG Eclipse Plugin

Looking at p2 metadata, I see that expected MD5 of this bundle is `437e2fde4ad799bf47eefb861325b974`. So, for some reason, you're actually downloading something that is not expected.

**Comment by manandbytes** [comment]
> Problems downloading artifact: osgi.bundle,org.apache-extras.beanshell.bsh.source,2.0.0.b6.
MD5 hash is not as expected. Expected: 437e2fde4ad799bf47eefb861325b974 and found e08459580c0086b3ec9d10b222268dcf."

#400 mentions `Artifact not found` for the same artifact.

**Comment by missedone** [comment]
it could be a temporary network issue either at your side or bintray side, if you still encounter the installation issue, pls try to install offline, see the trouble shooting:
https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md

**Comment by mstrahinski** [comment]
not sure what exactly causes it, but other people have been able to successfully install it, so I would close it. I'm still unable but don't have the time to investigate it further as it already works with the previous version.

**Comment by shivaidrive** [comment]
Unable to install TestNG in windows 10 in my office but it works fine in Home system.
Following error throws
An error occurred while collecting items to be installed
session context was:(profile=C__Users_Shiva_eclipse_java-2019-06_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Problems downloading artifact: osgi.bundle,org.apache-extras.beanshell.bsh.source,2.0.0.b6.
MD5 hash is not as expected. Expected: 437e2fde4ad799bf47eefb861325b974 and found e08459580c0086b3ec9d10b222268dcf.
