### ISSUE TITLE
eclipse plugin generates invalid java for toString & hashCode

### ISSUE THREAD

**Issue by dabraham02124** [cbeust/testng-eclipse#407]
### Problem Statement
When the TestNG plugin for eclipse creates tests for toString & hashCode it generates methods with the signature "public void hashCode()" & "public void toString()".  This is not legal java.

Personally I'd like an option to simply append "Test" to the name of every method when creating a test, not just these two.

### Any relate message in "Error Log" view
None

### The Dependency Management tool for your project
- [X] Maven

### Operating System
- [X] OSX

**Comment by missedone** [comment]
@dabraham02124 , thanks for reporting this, it fixed, pls verify in the beta update-site channel:
https://dl.bintray.com/testng-team/testng-eclipse/updatesites/7.0.0.201812150659/
