### ISSUE TITLE
Browse for tests takes a while in large projects

### ISSUE THREAD

**Issue by thexfed** [cbeust/testng-eclipse#41]
I have a somewhat large project that I've been testing with TestNG.  The project has about 1000 source files (main source + tests) and 47 libraries linked.  When I'm running a test and click Browse in the TestNG Run Configuration (for either Class, Method, Groups, or Package) it takes about a minute and a half to show a list.  

I've messed around with the project setup to see if something in particular slowed it down.  Each time I removed a few libraries, it sped up a little.  Likewise, when I removed some source folders, that sped it up as well.  I removed all libraries and it works in about 6 seconds.  If instead I remove most of my source and leave the libraries, it takes about 4 seconds.  It seems that the combination of a lot of source with several libraries cause it to slow way down.

**Comment by missedone** [comment]
fixed in PR #182
