### ISSUE TITLE
After adding module-info.java, testng-eclipse no longer finds test classes in maven project

### ISSUE THREAD

**Issue by olovm** [cbeust/testng-eclipse#410]
### Problem Statement
Using a minimal standard maven project with separate src and test folders runs as expected. As soon as I add a module-info.java file, testng-eclipse no longer finds the test class, see error message below. After adding module-info.java, the test still works as expected if run using maven (Run As / Maven test).

### Any relate message in "Error Log" view
[RemoteTestNG] revisions:
	git.commit.id=f7160ab
	git.build.version=1.3.1
	git.branch=f7160ab041ae763e01e10b6867b5d40d49e2688e
[RemoteTestNG] loaded class org.testng.internal.Version at file:/home/user/.m2/repository/org/testng/testng/6.14.3/testng-6.14.3.jar
[RemoteTestNG] detected TestNG version 6.14.3
[RemoteTestNG] Invoked with -serport 33033 -protocol json -d /home/user/eclipse-workspace201812rc1/dummy/test-output /tmp/testng-eclipse-1408864849/testng-customsuite.xml 
[BaseMessageSender] Waiting for Eclipse client on localhost:33033
[BaseMessageSender] Received a connection from Eclipse on localhost:33033
[BaseMessageSender] Connection established, starting reader thread
[BaseMessageSender] ReaderThread waiting for an admin message
org.testng.TestNGException: 
Cannot find class in classpath: org.xyz.DummyTest
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:77)
	at org.testng.xml.XmlClass.init(XmlClass.java:69)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:55)
	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:575)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
...

### The Dependency Management tool for your project

- [X ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ X] Linux
- [ ] OSX

**Comment by missedone** [comment]
Could you share a sample project for reproducing the issue? Thanks

**Comment by olovm** [comment]
https://github.com/olovm/modular
Clone and import this as a maven project, in eclipse with installed testng-eclipse. 
Trying to run tests with testng-eclipse fails with error as above.
Try to run tests using maven (Run as / maven test), works as expected.
Remove module-info.java, do a maven / update project.
Try to run test with testng-eclipse and it works as expected.
Put back / create a new module-info.java, do a maven / update project. 
Try to run test with testng-eclipse and the error is back.

I have tried this with eclipse 201809 using java 10, and java 11 (with installed support in eclipse), eclipse 201812rc1, with java 11.

**Comment by missedone** [comment]
thanks @olovm , i'll try to setup my dev env for java 11 first :)

**Comment by missedone** [comment]
@mbooth101, do you have Java 11 env setup on your machine? would you like to take a look at this issue?

**Comment by missedone** [comment]
@olovm , pls verify the fix in beta update site:
https://dl.bintray.com/testng-team/testng-eclipse/updatesites/7.0.0.201812210054/

**Comment by olovm** [comment]
Using eclipse 201812 with java 11, now works as expected for the stated problem when using the beta version of testng-eclipse.

Thank you!

**Comment by missedone** [comment]
thank you @olovm
