### ISSUE TITLE
Testng plugin cannot run Factory methods directly

### ISSUE THREAD

**Issue by real-borat-sagdiyev** [cbeust/testng-eclipse#415]
### Problem Statement
Yakshemash ! In eclipse with the testng plugin, Run-as testng test does not show up for methods with Factory annotation. But, I can run those methods by creating a suite xml file for them. Can you make it work from the run-as menu ?

More details here https://stackoverflow.com/questions/54057860/how-to-run-testng-factory-with-eclipse

### Project Details.
- [ ] Maven
- [ ] Eclipse Version: 2018-09 (4.9.0). Build id: 20180917-1800
- [ ] Testng plugin (version 6.14.0.201802161500)

### Operating System
- [ ] Windows 10 64 bit

Chenqui.

**Comment by missedone** [comment]
it looks to me an edge case and can be easily workaround, 
@juherr, @@krmahadevan, do you think it deserve the effort for implementing the feature?

**Comment by krmahadevan** [comment]
@missedone what is the workaround you have in mind ? I feel it would be good if this can be fixed. 
Especially when the same functionality works fine in Intellij but our own plugin doesn't support it.

**Comment by juherr** [comment]
@missedone It depends on the effort. I've no idea how much time it can cost.
But I agree with @krmahadevan, ideally, we should have the same features than IntelliJ or more.

**Comment by missedone** [comment]
@real-borat-sagdiyev , could you try with beta update site:
https://dl.bintray.com/testng-team/testng-eclipse/updatesites/7.0.0.201901200334/
