### ISSUE TITLE
Installations issues

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#421]
https://twitter.com/ant4u/status/1101527689578627074
https://stackoverflow.com/questions/55000314/eclipse-invalid-classpath-container-testng-in-project-and-junit-failed
https://stackoverflow.com/questions/55024045/unable-to-install-testng-from-eclipse-marketplace
Comments from https://marketplace.eclipse.org/content/testng-eclipse

I don't know if they are all related to the same issue.

**Comment by missedone** [comment]
well, i think they haven't yet tried the recent release 
https://github.com/cbeust/testng-eclipse/releases/tag/6.14.3.201902250526

**Comment by juherr** [comment]
I have the same supposition. Thank for the answer :) 👍
