### ISSUE TITLE
Unable to install TestNG to eclipse: Getting 502 error for both URLs

### ISSUE THREAD

**Issue by Ganpal** [cbeust/testng-eclipse#423]
From Eclipse Market place, Unable to install TestNG: Getting HTTP Server 'Bad Gateway': http://beust.com/eclipse

**Comment by Ganpal** [comment]
Same issue with this URL ...  https://dl.bintray.com/testng-team/testng-eclipse...

**Comment by missedone** [comment]
could you retry, it might be network glitch, 
or, you can download the update-size archive then install offline
https://github.com/cbeust/testng-eclipse#update-sites

**Comment by stanio** [comment]
For what is worth, the [_Download_](https://testng.org/doc/download.html) page refers to:

> http://beust.com/eclipse

→ 301 Moved Permanently: http://dl.bintray.com/testng-team/testng-eclipse-release/

> http://beust.org/eclipse-beta

→ 404 Not Found

Note the domain name `beust.org` vs. `beust.com`:

http://beust.com/eclipse-beta

→ 301 Moved Permanently: http://dl.bintray.com/testng-team/testng-eclipse/

**Comment by cbeust** [comment]
This typo has probably been here for years, amazing nobody noticed it so far. Nice catch, @stanio  :)

This is fixed.

Thanks!
