### ISSUE TITLE
TestNG cannot be installed on recent versions of Eclipse 2019-03 via Eclipse Marketplace

### ISSUE THREAD

**Issue by nturner** [cbeust/testng-eclipse#429]
The Eclipse Marketplace page for TestNG is https://marketplace.eclipse.org/content/testng-eclipse

This page allows installing the TestNG plugin, but it seems like it has not been updated in a long time. The most recent version of Eclipse that is supported is listed as 2018-09 (4.9). Since then, Eclipse 2018-12 has been released, and more recently Eclipse 2019-03 has been released.

Is the TestNG Eclipse plugin still an active project, or is it no longer maintained?

**Comment by missedone** [comment]
@cbeust , could you update the eclipse marketplace page?
thanks

**Comment by missedone** [comment]
TestNG Eclipse plugin is under maintained, it's stable enough so you don't see much commit activities on the repo.
Feel free to create feature request and/or issue.

closing the ticket now since the Marketplace page is getting updated, thanks @cbeust

**Comment by rodwiddowson** [comment]
As of a few seconds ago TestNG is (still) showing as incompatible with 2019-03.  Any ETA for the marketplace update?  Thanks tnx

**Comment by missedone** [comment]
@cbeust , pls add 2018-12 (4.10) and 2019-03 (4.11) to the Eclipse Version list, thanks

**Comment by jontejj** [comment]
FYI I also had problems with this. I finally got it working by using http://beust.com/eclipse as an update site. The https version does NOT work!

**Comment by jontejj** [comment]
And the reason I tried with https was because it's listed on https://testng.org/doc/download.html

**Comment by jbauerrfid** [comment]
> As of a few seconds ago TestNG is (still) showing as incompatible with 2019-03. Any ETA for the marketplace update? Thanks tnx
> 
> Although this is on windows It still fails when run from an elevated prompt.

This bug also appears on Linux (Ubuntu)

**Comment by escay** [comment]
The same still happens on Eclipse version 2019-06 on Windows 10.
Using the workaround http://beust.com/eclipse as an update site worked for me.

**Comment by missedone** [comment]
closing this since 2019-03 support is added to marketplace, let's trace 2019-06 support on #434

**Comment by Smyrna15** [comment]
I still have the same issue TestNG cannot be installed on recent versions of Eclipse 2019-03 via Eclipse Marketplace windows 10

**Comment by missedone** [comment]
@Smyrna15 , pls install from the update site: https://dl.bintray.com/testng-team/testng-eclipse-release

I don't have access to update marketplace, @cbeust does.

**Comment by Smyrna15** [comment]
What should I do? please help me

[image: 2020-03-27_20h50_06.png]

**Comment by missedone** [comment]
you can follow the instructions here but use the released update site url above:
https://github.com/cbeust/testng-eclipse#install-snapshot

**Comment by Ogorodin** [comment]
> 
> 
> you can follow the instructions here but use the released update site url above:
> https://github.com/cbeust/testng-eclipse#install-snapshot

This solved it for me, thank you missedone, cheers

**Comment by TKL-FC** [comment]
I had the same Problem with Eclipse 2020-06.
https://www.techbeamers.com/install-testng-in-eclipse-ide/#method3
worked for me.
