### ISSUE TITLE
In Eclipse Java build path - Not able to add TestNG library.

### ISSUE THREAD

**Issue by mohamedece09** [cbeust/testng-eclipse#430]
In Eclipse Java build path - Not able to add TestNG library. Please help me to solve this.

I am using Eclipse Neon version. 
I have added TestNG dependency(6.14.3)  in my POM.xml.
I have installed TestNG plugin and TestNG M2E integration plugin.

Please find the below screenshot,

![image](https://user-images.githubusercontent.com/50018712/57527765-252f2200-734e-11e9-8f47-2f9b7819fd31.png)

![image](https://user-images.githubusercontent.com/50018712/57527867-5b6ca180-734e-11e9-8352-48f69020634a.png)

**Comment by missedone** [comment]
@mohamedece09 , pls fix your plugin installation first, i highlight here:
https://github.com/cbeust/testng-eclipse/issues/428#issuecomment-490960525

**Comment by missedone** [comment]
second thing is now that you use Maven manage the project dependencies, you need to put the testng in your pom.xml, rather than adding local library

**Comment by mohamedece09** [comment]
It is working fine now. I just changed testNG plugin from 6.14.3 to 6.9.11

**Comment by devi386** [comment]
Hi sir,
    My Name is Devi testNG not install my Eclipse.
    1.EclipseMarketPlace not working some error msg.
    2.New Software install testNG plugin but some error msg.
  
   a. Java  version : 21 (java version already using : 11,17,24)
   b. Maven version : 3.9.9
   c. Eclipse latest version : 4.35.0
   d. Windows : 11
      i'm attached screenshots please solow my problem.

![Image](https://github.com/user-attachments/assets/5211e9d5-79d6-4b63-91a9-1abebf1cfd32)
![Image](https://github.com/user-attachments/assets/fc146579-faed-4bf1-8992-091b4f36908f)

**Comment by missedone** [comment]
@devi386 , could you try to install with the offline updatesite https://testng.org/testng-eclipse-update-site/zipped/7.11.0.202503091801/org.testng.eclipse.updatesite.zip

**Comment by devi386** [comment]
not working.
