### ISSUE TITLE
Unable to install TestNG in Eclipse, showing an error Unable to read  Repository at https://beust.com/eclipse/content.xml.

### ISSUE THREAD

**Issue by goelsri** [cbeust/testng-eclipse#433]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first

**Comment by SuperPat45** [comment]
Eclipse can not install because the URL https://dl.bintray.com/testng-team/testng-eclipse//content.xml return Error 404 and Test NG is not in marketplace of the new version 4.12 (19.06)

**Comment by missedone** [comment]
closing this since no reply from OP
