### ISSUE TITLE
TestNG 7 beta does not work with Eclipse 4.12 (2019-06)

### ISSUE THREAD

**Issue by SuperPat45** [cbeust/testng-eclipse#434]
### Problem Statement
TestNG 7.0.0.201902250541
Eclipse 4.12 (2019-06)
OpenJDK 11

After migration to eclipse 4.12 (2019-06) I have installed the Test NG plugin using t(he url  https://dl.bintray.com/testng-team/testng-eclipse/ (As TestNG was not available on the Marketplace for this eclipse version)

I added the library "TestNG" in hte classpath.
I have the error:
> Invalid classpath container: 'TestNG' in project

My test classes show errors:
> The import org.testng cannot be resolved.

### Any relate message in "Error Log" view

I can not run the test using eclipse because of error:
> An internal error occurred during: "Launching VOCacheTest".
> java.lang.NullPointerException
> 	at org.eclipse.jdt.launching.JavaRuntime.computeDefaultContainerEntries(JavaRuntime.java:1593)
> 	at org.eclipse.jdt.launching.JavaRuntime.computeDefaultContainerEntries(JavaRuntime.java:1533)
> 	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspathEntry(JavaRuntime.java:1264)
> 	at org.eclipse.jdt.launching.StandardClasspathProvider.resolveClasspath(StandardClasspathProvider.java:95)
> 	at org.eclipse.jdt.launching.JavaRuntime.resolveRuntimeClasspath(JavaRuntime.java:1657)
> 	at org.eclipse.jdt.launching.AbstractJavaLaunchConfigurationDelegate.getClasspath(AbstractJavaLaunchConfigurationDelegate.java:431)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.getClasspath(TestNGLaunchConfigurationDelegate.java:370)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.createVMRunner(TestNGLaunchConfigurationDelegate.java:215)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launchTypes(TestNGLaunchConfigurationDelegate.java:156)
> 	at org.testng.eclipse.launch.TestNGLaunchConfigurationDelegate.launch(TestNGLaunchConfigurationDelegate.java:93)
> 	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:862)
> 	at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:720)
> 	at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1020)
> 	at org.eclipse.debug.internal.ui.DebugUIPlugin$2.run(DebugUIPlugin.java:1234)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [X] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X] Windows
- [ ] Linux
- [ ] OSX

**Comment by mtafseerhaider** [comment]
I am facing the same issue.

**Comment by mtafseerhaider** [comment]
I just solve this issue using https://dl.bintray.com/testng-team/testng-eclipse-release/6.14.3/ in eclipse.
Beta version not stable yet to run with Eclipse 1.12

**Comment by SuperPat45** [comment]
With the stable version It works. trhanks

**Comment by campao** [comment]
I have the same issue. 

I'm using eclipse IDE (2019-06) and testNG 7.0 beta, because there where a bug with NPE in this 6.14.3 version, so i can't built my project with cmd line. But with the version testNG 7.0 beta i can't build in eclipse also. 

I already explained my situtation [there](https://stackoverflow.com/questions/57035692/eclipse-used-testng-7-without-built-with-maven-classpath-issue?noredirect=1#comment100628586_57035692), so you can find my errors.   

For the moment, I re installed the version 6.14.3, to build my code in eclipse and test it. ( I working again) But if there is solution for build my project in eclipse and in cmd line also, wich version can I used? 

Thanks for help !

**Comment by missedone** [comment]
i'm prepare the release of testng eclipse plugin for 7.0.0, see PR #441 
will update here soon

**Comment by missedone** [comment]
closing this, duplicates with #445 , pls try latest release. thx
