### ISSUE TITLE
NOt able to Install On latest Eclipse version

### ISSUE THREAD

**Issue by ADMHARSH** [cbeust/testng-eclipse#439]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by escay** [comment]
I just downloaded Eclipse 2019-06 (eclipse-java-2019-06-R-win32-x86_64) on Windows 10

I could not install the TestNg plugin using the marketplace.

But I could install the TestNg plugin using update site:
http://dl.bintray.com/testng-team/testng-eclipse/7.0.0/

If you want another version you could probably use update site:
http://beust.com/eclipse-beta
and browse around the versions.

**Comment by missedone** [comment]
@cbeust , pls update marketplace as soon as possible, people are suffering with this.

/duplicates #434

**Comment by missedone** [comment]
closing this, let's track in #436
