### ISSUE TITLE
Testng.xml is not providing suggestions of tags which was working previously

### ISSUE THREAD

**Issue by tabhresh** [cbeust/testng-eclipse#440]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
When TestNG.xml is created with manual process after adding the following lines we open a tag and during that eclipse was giving suggestions of the choice you can opt based on the position of the pointer but now it's not doing with Eclipse 2019-03 and 2019-06 as well even after updation of all the software eclipse as well as testNG.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 
No error for the same

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [Yes] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [Yes ] Windows
- [ ] Linux
- [ ] OSX

![TestNG XML issue](https://user-images.githubusercontent.com/22336822/63148662-86d2ec80-c01f-11e9-97cd-49e6ee9f5ae6.png)
[Error Sample.txt](https://github.com/cbeust/testng-eclipse/files/3508373/Error.Sample.txt)

**Comment by missedone** [comment]
i'm not aware of any such feature in Testng eclipse plugin.
it might be something of eclipse wtp plugins.
