### ISSUE TITLE
TestNG Version - 7.0.0 - Bug

### ISSUE THREAD

**Issue by Madhusudan-Devaraju** [cbeust/testng-eclipse#444]
### Problem Statement
1. Not able to open existing GIT project.
2. Get null pointer exception every time when the eclipse is closed.

### Any relate message in the "Error Log" view
I get null pointer exception while closing the eclipse.

### The Dependency Management tool for your project
Eclipse  2019-06 version 

### Operating System
(Windows 10 - 64 bit)

![TestNG-7 0 0 - error while closing the eclipse](https://user-images.githubusercontent.com/32246035/63546160-bc5b6680-c546-11e9-8e47-b8adb3a2c014.PNG)
![TestNG-7 0 0-Error-Eclipse-MavenProject-Windows10](https://user-images.githubusercontent.com/32246035/63546161-bcf3fd00-c546-11e9-99a0-df641b917c11.PNG)

###Please help me to resolve this ASAP.

Best Regards,
Madhu

**Comment by missedone** [comment]
what's the testng eclipse plugin version?
what's the testng version in your project?

**Comment by Madhusudan-Devaraju** [comment]
@missedone 

TestNG - 7.0.0.

I just updated the testNG from 6.14.3 to 7.0.0 and the above issue surfaced.
When I downgraded from 7.0.0 to 6.14.3, I dint any issues.

**Comment by missedone** [comment]
closing this, duplicates with #445, pls try with latest release 7.0.0.201908240652

**Comment by Madhusudan-Devaraju** [comment]
This is working fine now. Thanks.
