### ISSUE TITLE
TestNG-Eclipse show multiple duplicate entries for test execution

### ISSUE THREAD

**Issue by sachsgit** [cbeust/testng-eclipse#455]
### Problem Statement
When I execute N number of tests within a testng suite, the "results of running suite" shows that the 1st test ran N times (mere duplicates), the second test ran for N-1 times (mere duplicates), until the Nth test ran once.

### Any relate message in "Error Log" view
> null
> org.eclipse.m2e.logback.appender
> Error
> Fri Sep 06 11:49:19 EDT 2019
> Project org.penfed.selenium classifier tests resolved to wrong project at /org.penfed.selenium/target/test-classes

Happened at the beginning of the execution

### The Dependency Management tool for your project

- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X] Windows
- [ ] Linux
- [ ] OSX

**Comment by r4f431007** [comment]
Happening the same on 7.0.0 testNG

**Comment by nzall** [comment]
I have the same issue using Eclipse, with testng 7.1.0 on my classpath and the Eclipse TestNG plugin 7.0.0 installed.

**Comment by aeendale** [comment]
Looks like this was fixed in testng 7.3.0

**Comment by missedone** [comment]
link https://github.com/cbeust/testng/issues/2243#issuecomment-718799929

pls update to testng 7.3.0
