### ISSUE TITLE
Maven : Archetype error while creating Maven project in Java

### ISSUE THREAD

**Issue by poonam26s** [cbeust/testng-eclipse#456]
I am trying to create a Maven Project in Java but it is showing error :
**_Could not resolve artifact org.apache.maven.archetypes:maven-archetype-quickstart:pom:1.1_** while creating a project

Below are the details:
Java - 1.8.0
Eclipse - 2018-19 (4.9.0)
Maven - apache-maven-3.6.1
OS - Windows

**Comment by kamlakant** [comment]
@poonam26s How is this related to TestNG?

**Comment by poonam26s** [comment]
@kamlakant I know it’s not related to testing. Just wanted to get solution if anyone had faced same issue with Maven + TestNG

**Comment by missedone** [comment]
you can create the maven project with mvn cli on your terminal.
