### ISSUE TITLE
compatible issue

### ISSUE THREAD

**Issue by aswin-dev** [cbeust/testng-eclipse#463]
![compalityissue](https://user-images.githubusercontent.com/54928705/66566320-49539100-eb82-11e9-8c9c-26dc1c656135.png)
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

[issue.txt](https://github.com/cbeust/testng-eclipse/files/3712382/issue.txt

i cant install Test-NG  due to compatible issue please fix this issue if i use old version of eclipse some 
feature of framework is not working properly

**Comment by missedone** [comment]
![image](https://user-images.githubusercontent.com/555134/66719597-e3941e80-eda6-11e9-8a87-b5632815c52c.png)
testng eclipse plugin is compatible  with Eclipse-2019-09.

what's the testng eclipse version you used? what's the detail error msg?

**Comment by missedone** [comment]
Thanks for sharing it , seems setting issue at marketplace.

**Comment by melloware** [comment]
I think the testng identifier needs to be updated saying it supports the latest Eclipse and then it will be allowed in the MarketPlace to install for 2019-09 again.

**Comment by melloware** [comment]
Similar to this issue i had on another plugin apparently the owner of TestNG plugin has to log into the MarketPlace and update the MetaData to fix it.
See: https://github.com/maximeAudrain/jenerate/issues/23

**Comment by missedone** [comment]
@cbeust pls fix it on marketplace, thx

**Comment by missedone** [comment]
closing, duplicates with #436
