### ISSUE TITLE
I have installed testng with the version 7.0.0 facing an error detected TestNG version 7.0.0 java.lang.NoSuchMethodError: org.testng.remote.AbstractRemoteTestNG.addListener(Lorg/testng/ISuiteListener;)V 	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:111) 	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251) 	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

### ISSUE THREAD

**Issue by Divyasuresh311** [cbeust/testng-eclipse#465]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
could you try the latest version if you haven't yet
https://github.com/cbeust/testng-eclipse/releases/tag/7.0.0.201908240652

**Comment by sandeepnegi1996** [comment]
Hi,

I have tried with the latest version of eclipse but it is also not able to install the testng plugin then I have switched back to **eclipse photon** and everything is working just fine
