### ISSUE TITLE
TestNG plugin is not available in "‘http://beust.com/eclipse" also testng.org site is not openning

### ISSUE THREAD

**Issue by HDwares** [cbeust/testng-eclipse#467]
### Problem Statement
TestNG plugin is not available in "‘http://beust.com/eclipse" also testng.org site is not openning

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

Receiving below error in eclipse:
![image](https://user-images.githubusercontent.com/49922820/70017608-9152cb00-15a9-11ea-9eff-bc7197188a45.png)

### The Dependency Management tool for your project
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows

**Comment by vvijayaranivj** [comment]
Unable to add the testng plugin to eclipse, is there any other alternative, kindly help.

Thanks in advance,
Vijaya.

**Comment by leilachebbah** [comment]
you can try with this link: http://dl.bintray.com/testng-team/  @HDwares , @vvijayaranivj

**Comment by vvijayaranivj** [comment]
This URL worked for me, thanks a ton!

**Comment by missedone** [comment]
thanks @leilachebbah , yes, the official testng eclipse plugin now hosts on bintray:
http://dl.bintray.com/testng-team/testng-eclipse/

**Comment by dmacx2** [comment]
http://dl.bintray.com/testng-team/testng-eclipse/ dont exists

**Comment by missedone** [comment]
Hi pls check #511 , we are moving the update site to GitHub due to the bintray sunset
