### ISSUE TITLE
[improvement] add code mining annotations for TestNG tests

### ISSUE THREAD

**Issue by gayanper** [cbeust/testng-eclipse#483]
With eclipse 4.8 there is support for showing actions which is called code mining https://www.eclipse.org/eclipse/news/4.8/platform_isv.php

Its would be nice to have Run and Debug actions on TestNG test classes and test methods like the JUnit test cases has which are provided by the eclipse JUnit plugin.

I would really like to help you out here with a PR if you think this is a good feature to have in this plugin.

**Comment by missedone** [comment]
@gayanper , yes that's really a good feature, and appreciate if you can raise a PR. thanks

**Comment by gayanper** [comment]
@missedone Do you think we should create a new feature and add requirment for that feature so that it should only be installed eclipse photon or above, or should we add the feature into the main plugin since the plugin is already depending on photon ?

I have implemented the mining so that it works.

**Comment by missedone** [comment]
@gayanper , let's add it to the main plugin since yes Photon and above is hard requirement now. thanks

**Comment by gayanper** [comment]
Its passing with the last push i did.

**Comment by gayanper** [comment]
@missedone can we release this feature ?

**Comment by missedone** [comment]
released now, thanks
