### ISSUE TITLE
DebugAs NGTest gives Error: could not open ".testng-arguments.txt" 

### ISSUE THREAD

**Issue by bodote** [cbeust/testng-eclipse#489]
### Problem Statement
**I did read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**
have a simple hello-world gradle/testng project. 
Eclipse 20 03 and lastest testng plugin (7.1.1) 
"gradle test" on the command line works
however wenn I choose "Debug As NG Test" in Eclipse on my simple Hello World - testng class it does not connect zu the Eclipse debugger and instead gives this error message:
![Bildschirmfoto 2020-04-15 um 13 42 28](https://user-images.githubusercontent.com/8531026/79333623-26ce7600-7f1f-11ea-8575-26ecb7635abb.png)
Error: could not open `.testng-arguments.txt'

so where should this `.testng-arguments.txt' come from anyway?
it is not there . do i need to write it on my own ? if yes : what to put into it? Could not found any docu on that not anything related with `.testng-arguments.txt'  on google.

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

!ENTRY org.testng.eclipse 1 0 2020-04-15 13:49:00.307
!MESSAGE [TestNGLaunchConfigurationDelegate] Launching:
  Classpath: /Applications/Eclipse2020-03.app/Contents/Eclipse/configuration/org.eclipse.osgi/1047/0/.cp/lib/testng-remote.jar /Users/bodo/eclipse-ws-2020-03/ng_test2/bin/main /Users/bodo/eclipse-ws-2020-03/ng_test2/bin/test /ng_test2/bin/default /Users/bodo/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.6.1/e4ba98f1d4b3c80ec46392f25e094a6a2e58fcbf/commons-math3-3.6.1.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/28.0-jre/54fed371b4b8a8cce1e94a9abd9620982d3aa54b/guava-28.0-jre.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.guava/failureaccess/1.0.1/1dcf1de382a0bf95a3d8b0849546c88bac1292c9/failureaccess-1.0.1.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/2.8.1/eb2e8ab75598548cc8acf9a1ca227e480e01881e/checker-qual-2.8.1.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.3.2/d1a0c5032570e0f64be6b4d9c90cdeb103129029/error_prone_annotations-2.3.2.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.3/ba035118bc8bac37d7eff77700720999acd9986d/j2objc-annotations-1.3.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.17/f97ce6decaea32b36101e37979f8b647f00681fb/animal-sniffer-annotations-1.17.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/org.testng/testng/7.1.0/7504709f2d0b6e5070d1c6a0cae6c1c605489f8/testng-7.1.0.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/faf9ee8ac09eafd1128091426dd367a8c0085d55/guice-4.1.0-no_aop.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.72/6375e521c1e11d6563d4f25a07ce124ccf8cd171/jcommander-1.72.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.21/18775fdda48574784f40b47bf478ab0593f92e4d/snakeyaml-1.21.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar /Users/bodo/.gradle/caches/modules-2/files-2.1/aopalliance/aopalliance/1.0/235ba8b489512805ac13a8f9ea77a1ca5ebe3e8/aopalliance-1.0.jar
  VMArgs:    -ea @.testng-arguments.txt
  Class:     org.testng.remote.RemoteTestNG
  Args:      -serport 55841 -protocol json -d /Users/bodo/eclipse-ws-2020-03/ng_test2/test-output /var/folders/7b/nw03n2v92r9gg64crzt119bw0000gn/T/testng-eclipse-1613556873/testng-customsuite.xml
java -ea @.testng-arguments.txt -classpath /Applications/Eclipse2020-03.app/Contents/Eclipse/configuration/org.eclipse.osgi/1047/0/.cp/lib/testng-remote.jar:/Users/bodo/eclipse-ws-2020-03/ng_test2/bin/main:/Users/bodo/eclipse-ws-2020-03/ng_test2/bin/test:/ng_test2/bin/default:/Users/bodo/.gradle/caches/modules-2/files-2.1/org.apache.commons/commons-math3/3.6.1/e4ba98f1d4b3c80ec46392f25e094a6a2e58fcbf/commons-math3-3.6.1.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/28.0-jre/54fed371b4b8a8cce1e94a9abd9620982d3aa54b/guava-28.0-jre.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.guava/failureaccess/1.0.1/1dcf1de382a0bf95a3d8b0849546c88bac1292c9/failureaccess-1.0.1.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/b421526c5f297295adef1c886e5246c39d4ac629/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.code.findbugs/jsr305/3.0.2/25ea2e8b0c338a877313bd4672d3fe056ea78f0d/jsr305-3.0.2.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/org.checkerframework/checker-qual/2.8.1/eb2e8ab75598548cc8acf9a1ca227e480e01881e/checker-qual-2.8.1.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.errorprone/error_prone_annotations/2.3.2/d1a0c5032570e0f64be6b4d9c90cdeb103129029/error_prone_annotations-2.3.2.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.j2objc/j2objc-annotations/1.3/ba035118bc8bac37d7eff77700720999acd9986d/j2objc-annotations-1.3.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/org.codehaus.mojo/animal-sniffer-annotations/1.17/f97ce6decaea32b36101e37979f8b647f00681fb/animal-sniffer-annotations-1.17.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/org.testng/testng/7.1.0/7504709f2d0b6e5070d1c6a0cae6c1c605489f8/testng-7.1.0.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.1.0/faf9ee8ac09eafd1128091426dd367a8c0085d55/guice-4.1.0-no_aop.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/com.beust/jcommander/1.72/6375e521c1e11d6563d4f25a07ce124ccf8cd171/jcommander-1.72.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/org.yaml/snakeyaml/1.21/18775fdda48574784f40b47bf478ab0593f92e4d/snakeyaml-1.21.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/javax.inject/javax.inject/1/6975da39a7040257bd51d21a231b76c915872d38/javax.inject-1.jar:/Users/bodo/.gradle/caches/modules-2/files-2.1/aopalliance/aopalliance/1.0/235ba8b489512805ac13a8f9ea77a1ca5ebe3e8/aopalliance-1.0.jar org.testng.remote.RemoteTestNG -serport 55841 -protocol json -d /Users/bodo/eclipse-ws-2020-03/ng_test2/test-output /var/folders/7b/nw03n2v92r9gg64crzt119bw0000gn/T/testng-eclipse-1613556873/testng-customsuite.xml

!ENTRY org.eclipse.jdt.launching 4 116 2020-04-15 13:49:00.375
!MESSAGE Error: could not open `.testng-arguments.txt'

!ENTRY org.testng.eclipse 1 0 2020-04-15 13:49:14.797
!MESSAGE Stop the socket server as it's still pending on accepting the client

### The Dependency Management tool for your project

- [ ] Maven
- [x ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [ x] OSX

**Comment by missedone** [comment]
> java -ea @.testng-arguments.txt -classpath /Applications/Eclipse2020-03.app/Contents/Eclipse/configuration/org.eclipse.osgi/1047/0/.cp/lib/testng-remote.jar...

testng eclipse plugin does not use `testng-arguments.txt`, and check the command line above, see something being added in your test launch configuration.

**Comment by bodote** [comment]
thanks! Yes, in "Preferences->TestNG->Run/Debug" in Field "JVM args" there was the entry "@testng-arguments.txt"
that leaves me with the question , why this is set (by default?, since i did not add this)  to this value anyway ?

**Comment by missedone** [comment]
Testng plugin doesn’t set this value.
