### ISSUE TITLE
[RemoteTestNG] detected TestNG version 7.0.1 Exception in thread "main" java.lang.NoClassDefFoundError: com/google/inject/Stage

### ISSUE THREAD

**Issue by ritac506** [cbeust/testng-eclipse#492]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
duplicates with #472
