### ISSUE TITLE
Source not found while debugging in Eclipse.

### ISSUE THREAD

**Issue by GoldSpeci** [cbeust/testng-eclipse#494]
Trying to debug with Eclipse and TestNg a Maven project.

Every class I start (debug mode) in the same project I get the screen "Source not found".
By selecting the right folder it than works as expected. The problem is, I have to do it with every single class that belongs to the same project.
Running the class in debug afterwards works fine.
The project is in the Eclipse workspace.

Creating a Maven project and debugging as Java Application runs as expected.

Just tried out, no error with Eclipse 2019-06 Build id: 20190614-1200

Here my setup.

Eclipse IDE for Enterprise Java Developers.

Version: 2020-03 (4.15.0)
Build id: 20200313-1211

Testng plugin for Eclipse
Tested with 7.1 and 7.2 both have the same behavior.

Testng version 7.1.0

java.version=1.8.0_221
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments: -product org.eclipse.epp.package.jee.product
Command-line arguments: -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product
- [ x] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ x] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
duplicates with #490

see https://github.com/cbeust/testng-eclipse/issues/490#issuecomment-615279553

**Comment by GoldSpeci** [comment]
Thanks a lot and sorry, didn't see the 490.
