### ISSUE TITLE
TestNG codemining cause a NPE in code mining chain 

### ISSUE THREAD

**Issue by gayanper** [cbeust/testng-eclipse#496]
For non tests classes the code mining provider for testng return null. This cause a break in the code mining chain. This is something we missed when implementing the codeminings in the initial stage.

**Comment by missedone** [comment]
hi @gayanper  thanks for for the quick fix, it's released now: https://github.com/cbeust/testng-eclipse/releases/tag/7.2.0.202005051752

**Comment by gayanper** [comment]
Thanks Nick
