### ISSUE TITLE
Source files are not included in "Default" source path

### ISSUE THREAD

**Issue by AlekseyMalyshev** [cbeust/testng-eclipse#500]
### Problem Statement
Older version of the plugin would add paths to Java source files to "Default" Source path. Current version only adds paths to target classes (see attached image). Now every time I start debugging a new test case, I have to add project path manually (Add -> Project, etc.).

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [X ] Maven
- [X ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X ] OSX
<img width="654" alt="Screen Shot 2020-05-24 at 2 16 43 PM" src="https://user-images.githubusercontent.com/739471/82756411-d16d6a80-9de2-11ea-8bfd-c7c5cd34fcd8.png">

Eclipse Version: 2020-03 (4.15.0) Build id: 20200313-1211
TestNG Version: 7.2.0 (also tested with the same result with 6.14.3)

**Comment by missedone** [comment]
@AlekseyMalyshev , could you check https://github.com/cbeust/testng-eclipse/issues/490#issuecomment-615279553

**Comment by AlekseyMalyshev** [comment]
@missedone it worked. Thank you.
