### ISSUE TITLE
DebugAs - TestNG: Can not find source code

### ISSUE THREAD

**Issue by xavipen** [cbeust/testng-eclipse#503]
### Problem Statement

I use Debug As --> TestNG to execute a test with a breakpoint in it. The breakpoint is in the test code itself. 

When the execution gets to the breakpoint appears a screen saying "source not found" and a button to "Edit Source Lookup Path..." instead of the code with the breakpoint. 

This is the message eclipse shows when the source code can not be found but it should be found as it is the test code that should be displayed.

This happened with version 7.1.0 and I have updated to version 7.2.0 with the same result. The eclipse version is 2020-03 and a college also experience the same problem with eclipse 2020-06.

### The Dependency Management tool for your project
- [X] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [X] Windows
- [ ] Linux
- [ ] OSX

**Comment by missedone** [comment]
duplicates #490 

pls check https://github.com/cbeust/testng-eclipse/issues/490#issuecomment-615279553

**Comment by xavipen** [comment]
Thanks! I did not see that one.
