### ISSUE TITLE
TestNG is not compatible with Eclipse 4.16

### ISSUE THREAD

**Issue by Kcchouette** [cbeust/testng-eclipse#506]
### Problem Statement

TestNG 7.3.0 is not compatible with Eclipse 4.16.X

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [x] Linux
- [ ] OSX

**Comment by Kcchouette** [comment]
See report from comment section of marketplace too https://marketplace.eclipse.org/comment/7080#comment-7080

**Comment by missedone** [comment]
closing, duplicates with #436
