### ISSUE TITLE
new p2 repo to replace bintray

### ISSUE THREAD

**Issue by guillaumecle** [cbeust/testng-eclipse#511]
JFrog is announcing Bintray sunset and that is where TestNG eclipse plugins are served.
A new p2 hosting service is need to replace it.

**Comment by missedone** [comment]
@guillaumecle , thanks for the reminder.
yes, we're evaluating the free option to host the TestNG eclipse plugins, for now i'm thinking of host on github.
do you happen to know any other option?

Thanks

**Comment by guillaumecle** [comment]
No sorry, I don't have any recommendation.

**Comment by missedone** [comment]
http://www.lorenzobettini.it/2021/03/publishing-an-eclipse-p2-composite-repository-on-github-pages/
> sites have a soft bandwidth limit of 100GB per month and sites have a soft limit of 10 builds per hour

the bandwidth limit might be an issue
CC @cbeust @juherr @krmahadevan

**Comment by juherr** [comment]
@missedone I think it is the best solution for, at least, the short term. 👍

**Comment by cbeust** [comment]
Yeah, I think the bandwidth will be a problem. As you know, my personal
site is still hammered by requests for our old Eclipse update site to the
point that my web host refused to handle it until I put it behind
Cloudflare... And that's for a URL that's no longer used.

But yes, this is definitely what we need to do right now.

-- 
Cédric

**Comment by krmahadevan** [comment]
@juherr @cbeust @missedone - Just a curious question. What if we moved away to making TestNG eclipse plugin available as an offline plugin that would need to be downloaded and installed in eclipse manually ?
That way we could publish the newer versions as releases on the github project and then we could may have some good document with screenshots that shows how to go about doing this, if the rate limiting on GitHub Pages is going to be a problem.

**Comment by cbeust** [comment]
Definitely something we should do anyway since there are quite a few users
who can't use p2 sites for firewall or other reasons.

-- 
Cédric

**Comment by missedone** [comment]
we will replace the bintray repository, for now as workaround we hosted the plugin update site on github, pls use this update site url: https://testng.org/testng-eclipse-update-site
the source is at https://github.com/testng-team/testng-eclipse-update-site

i will update the README.md shortly with new URL.

**Comment by SukumarSpotline** [comment]
@missedone Thanks a ton, it works and you made my day.

**Comment by missedone** [comment]
readme is updated to use new update site url.

@cbeust , could you update the url on eclipse marketplace with `https://testng.org/testng-eclipse-update-site`

**Comment by liorst99-IS** [comment]
Hi

Although The new Eclipse contain the new link: https://testng.org/testng-eclipse-update-site
, the new link doesn't work.

Even if the follow the steps:
1.	Click "Help -> Install New Software..." on top level menu 
2.	Paste the url https://testng.org/testng-eclipse-update-site

I got "Unable to read repository at https://testng.org/testng-eclipse-update-site/7.4.0/content.xml " Error

I will be great full for any assist.
Thanks a lot
Lior

**Comment by prb112** [comment]
@liorst99-IS it took a while for it to resolve for me.  and thank you for the nice note it helped me get to the plugin

**Comment by missedone** [comment]
@liorst99-IS , you may try with the specific version url: https://testng.org/testng-eclipse-update-site/7.4.0
BTW, the update site is hosted on GitHub with GitHub pages, there’s rate limit as link above. We are keep watching.

**Comment by cbeust** [comment]
Done!

https://marketplace.eclipse.org/content/testng-eclipse

-- 
Cédric

**Comment by missedone** [comment]
@cbeust , i see it's still old update-site: 
![image](https://user-images.githubusercontent.com/555134/117079404-8a753e00-acf0-11eb-9406-fbe630734bdb.png)

**Comment by liorst99-IS** [comment]
Hi. 
Thanks a lot for your support.
I have another question, if you can assist if will be great.
I download the latest eclipse version and it works fine.

I work with  Oxygen Release (4.7.0), It will be difficult to change the  eclipse version.
I got sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Is it make sense that the testNG doesn't support  Oxygen Release (4.7.0)?
Is the only solution to work with the latest Eclipse version?

Thanks a lot
Lior

**Comment by missedone** [comment]
@liorst99-IS , can you try download the update-site https://testng.org/testng-eclipse-update-site/zipped/7.4.0.202105021622/org.testng.eclipse.updatesite.zip and install from the archive on your local.

**Comment by liorst99-IS** [comment]
Really thanks a lot for all of you. For your great support.

Thanks a lot
Lior

**Comment by cbeust** [comment]
Ah yes, there was a second Save button. I saved it but now that download
button is greyed out... Wonder if it takes a bit to update.

-- 
Cédric

**Comment by missedone** [comment]
@cbeust thanks it works, just verified on a new eclipse instance. thx

**Comment by leerho** [comment]
[https://testng.org/testng-eclipse-update-site](https://testng.org/testng-eclipse-update-site) does not support 7.5 or 7.6.  When will they be supported?

**Comment by missedone** [comment]
hi @leerho , by the design we de-coupled the Eclipse Plugin and TestNG runtime, if you are asking for the TestNG runtime 7.5 and 7.6, they are available here  https://github.com/testng-team/testng-p2-update-site

**Comment by missedone** [comment]
BTW, seems the auto update of testng-p2 stops working after migration from bintray to github pages, will check and fix

**Comment by ShivamPandit1213** [comment]
Hi,
     Please help me with this ---

Your original request has been modified.
  "TestNG P2 Feature" is already installed, so an update will be performed instead.
Cannot complete the install because one or more required items could not be found.
  Software being installed: TestNG P2 Feature 7.9.0.r202312310341 (org.testng.p2.feature.feature.group 7.9.0.r202312310341)
  Missing requirement: slf4j-api 1.7.36 (slf4j.api 1.7.36) requires 'java.package; org.slf4j.impl 1.6.0' but it could not be found
  Cannot satisfy dependency:
    From: TestNG P2 Feature 7.9.0.r202312310341 (org.testng.p2.feature.feature.group 7.9.0.r202312310341)
    To: org.eclipse.equinox.p2.iu; slf4j.api [1.7.36,1.7.36]

**Comment by ShivamPandit1213** [comment]
After remove the link of dl.bantray
and update the above link no issue reflect but TestNG new version is not getting download. 

![Eclipse Issue](https://github.com/testng-team/testng-eclipse/assets/75351169/e33a2d1a-0f85-41a0-b757-c5124ecd75af)

**Comment by krmahadevan** [comment]
@ShivamPandit1213 - Please check if you have followed the below instructions https://testng.org/testng-eclipse/download

**Comment by ShivamPandit1213** [comment]
Eclipse Version: 2024-03 (4.31.0)
![eclipse market](https://github.com/testng-team/testng-eclipse/assets/75351169/a31d71ac-c2f3-4084-afcd-75ea6261a345)
