### ISSUE TITLE
403 Forbidden Error On All Downloads

### ISSUE THREAD

**Issue by melloware** [cbeust/testng-eclipse#516]
### Problem Statement
Getting 403 Forbidden on all BinTray downloads.

Just try: http://dl.bintray.com/testng-team/testng-eclipse-release/zipped/

![image](https://user-images.githubusercontent.com/4399574/114423090-d6671400-9b84-11eb-8549-3361a422fb85.png)

**Comment by yunusyakut** [comment]
i cant download from market place or install new software  getting forbidden issue

**Comment by datacore-jpatel** [comment]
I am getting the same issue

**Comment by jhosepv13** [comment]
I have the same issue, is someone know what happened?... I think yesterday was ok

**Comment by cbeust** [comment]
It's just bintray advancing toward shutting down completely.

-- 
Cédric

**Comment by devopsmikey** [comment]
What will replace repository http://dl.bintray.com/testng-team/testng-eclipse-release/ ?

**Comment by missedone** [comment]
hi guys, yes, we will replace the bintray repository, for now as workaround we hosted the plugin update site on github, pls use this update site url: https://testng.org/testng-eclipse-update-site
the source is at https://github.com/testng-team/testng-eclipse-update-site

i will update the README.md shortly with new URL.

**Comment by missedone** [comment]
links #511

**Comment by Sps-Ray** [comment]
Unforturnately, using update site url: https://testng.org/testng-eclipse-update-site suggested above doesn't seem to work. It just gets stuck, and it seems to keep trying dl.bintray.com. 
![testngInstallStuck](https://user-images.githubusercontent.com/47896416/116120284-4910dd00-a6b7-11eb-964f-0bf4735d9db8.PNG)

**Comment by missedone** [comment]
closing this ticket, duplicate with #511
