### ISSUE TITLE
Getting Forbidden error when access https://dl.bintray.com/testng-team/testng-eclipse/

### ISSUE THREAD

**Issue by sanoj-s** [cbeust/testng-eclipse#517]
### Problem Statement
Unable to install the latest plugin in Eclipse 2021-06 version. 

### Any relate message in "Error Log" view
eclipse.buildId=4.20.0.I20210407-1800
java.version=15.0.2
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.equinox.p2.metadata.repository
Error
Sun May 02 10:07:21 EDT 2021
No repository found at https://dl.bintray.com/testng-team/testng-eclipse-release/7.3.0/.

### Operating System

- [ ] Windows

**Comment by sanoj-s** [comment]
Able to download from https://testng.org/testng-eclipse-update-site/

**Comment by missedone** [comment]
duplicate with #511
