### ISSUE TITLE
UI glitches in eclipse with TestNG code minings

### ISSUE THREAD

**Issue by gayanper** [cbeust/testng-eclipse#521]
### Problem Statement
Write small test class as follows

```
package workbench;

import org.testng.annotations.Test;

public class TestCase
{
  @Test
  public void testFoo()
  {

  }

  @Test(dependsOnMethods = )
  public void testBoo() {
    
  }
}
```
when saving the file with incomplete annotation `@Test(dependsOnMethods = )`, the code mining are not rendered properly and the whole source rendering causes issues.

![image](https://user-images.githubusercontent.com/7471994/117274645-8a468100-ae5d-11eb-88dd-31dc24437dc8.png)

### Any relate message in "Error Log" view
No errors in the error view.

**Comment by gayanper** [comment]
@cbeust I can have a look at this if you want.

**Comment by missedone** [comment]
@gayanper , very appreciate if you can work on it, thanks

**Comment by gayanper** [comment]
This is a SWT issue in eclipse. closing this issue

**Comment by missedone** [comment]
Hi is the issues fixed in SWT?

**Comment by gayanper** [comment]
The issue is https://bugs.eclipse.org/bugs/show_bug.cgi?id=573016. Probably it will be included in 4.21 release. May be we can include a preference to switch off code mining for TestNG.

**Comment by missedone** [comment]
that sounds a good idea, would you like to raise a PR?
Thanks,
Nick

**Comment by gayanper** [comment]
Yes. Let me know how and where in preference panel you want the setting. I can add it.
