### ISSUE TITLE
Not able to install TestNG in Eclipse 

### ISSUE THREAD

**Issue by sainishubham724** [cbeust/testng-eclipse#522]
![Screenshot (341)](https://user-images.githubusercontent.com/82100073/118540236-07cb9480-b76e-11eb-96f5-4652d242d3ac.png)

not able to install TestNG in Eclipse. After calculating dependies it shows the error attached

**Comment by missedone** [comment]
@sainishubham724 , looks like your project doesn't managed by maven, and your eclipse doesn't have maven plugin installed, so pls just uncheck the "TestNG M2E (Maven) Integration" plugin, aka, just install TestNG plugin.
