### ISSUE TITLE
TestNG class throws  An internal error occurred during: "Launching TC01_GET".

### ISSUE THREAD

**Issue by AnithaMuvva** [cbeust/testng-eclipse#524]
Problem Statement
TestNG class throws  An internal error occurred during: "Launching TC01_GET".
Kindly help troubleshoot !!!
Eclipse Version: Eclipse Oxygen 3.0

 "Error Log" view
org.testng.eclipse.maven.MavenTestNGLaunchConfigurationProvider.getClasspath(Lorg/eclipse/debug/core/ILaunchConfiguration;)Ljava/util/List;

The Dependency Management tool for your project

 Maven
 Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

 Operating System

  Windows

**Comment by missedone** [comment]
hi @AnithaMuvva 
looks like you don't use Maven to manage your project dependencies, so pls uninstall the TestNG Maven integration plugin.
