### ISSUE TITLE
Security warning during instalation of TestNG plugin in Eclipse IDE

### ISSUE THREAD

**Issue by Panama585** [cbeust/testng-eclipse#528]
### Problem Statement
I'm on Windows. I got the latest version of the plugin. During the instalation of the TestNG plugin in Eclipse IDE, I receive security warning message: Installing unsigned software for which  authenticity or validity cannot be established. Continue with the installation?

![image](https://user-images.githubusercontent.com/61348243/126666346-02e699ee-592a-4c8e-8fdc-c9ad2b175efc.png)

**Comment by rr-nick-tan** [comment]
yes, we don't have gpg signing on the update site, pls ignore it and install anyway.

**Comment by rr-nick-tan** [comment]
closing this, let's track on issue #529

**Comment by meajaymalik** [comment]
Same error, not going forward without this
