### ISSUE TITLE
Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml. Permission denied: no further information

### ISSUE THREAD

**Issue by kanishkapundir** [cbeust/testng-eclipse#531]
### Problem Statement
**please read https://github.com/cbeust/testng-eclipse/blob/master/docs/Troubleshooting.md first**

### Any relate message in "Error Log" view
> "Windows -> Show View -> Others -> Error Log" 

### The Dependency Management tool for your project

- [ ] Maven
- [ ] Gradle
- [ ] Ant
- [ ] Eclipse Buildpath (aka. Use "TestNG Library" for your project in Eclipse)

### Operating System

- [ ] Windows
- [ ] Linux
- [ ] OSX

**Comment by juherr** [comment]
content.xml is not an existing file but compositeContent.xml is available.

I found 2 similar issues with potential solutions and it looks the issue is on your side:
https://github.com/knopflerfish/eclipse.knopflerfish.org/issues/5
https://github.com/subclipse/subclipse/issues/71

**Comment by vasu-stack** [comment]
Same issue plz suggest me

**Comment by snowymike** [comment]
the error eclipse shows is
```
Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
Unable to read repository at https://testng.org/testng-eclipse-update-site/content.xml.
Certificate for <testng.org> doesn't match any of the subject alternative names: [*.github.com, www.github.com, github.io, github.com, *.github.io, githubusercontent.com, *.githubusercontent.com]
```

**Comment by rr-nick-tan** [comment]
@snowymike @kanishkapundir looks like it's the ssl cert issue, as a quick workaround, you can download the zip updatesite, and install from local https://github.com/testng-team/testng-eclipse-update-site/tree/main/zipped

**Comment by missedone** [comment]
let's track on #529
