### ISSUE TITLE
classes with superclasses with test methods aren't detected as tests

### ISSUE THREAD

**Issue by The-Alchemist** [cbeust/testng-eclipse#70]
This is related to #47, I think, but not identical to.

### Steps to Reproduce
1. Create a test class with a test method (marked with `@Test`)
2. Create a subclass of the class in step (1) with NO test methods
3. Try Run->Run As...

TestNG Test will not be there.

### Sample Project
A [sample project](https://docs.google.com/open?id=0Bzjh30aiCt2JRjhBNE5BZ08wbHc) is available.

### More Info

I think there might be a bug in `TestSearchEngine.isTest()`.  I don't think it checks superclasses for any valid TestNG stuff.  I'll be happy to write a patch if someone gives me some direction. =)

**Comment by missedone** [comment]
fixed in PR #97
