### ISSUE TITLE
Run Configuration for a test of just a single method won't save load properly

### ISSUE THREAD

**Issue by FakeFakeFake** [cbeust/testng-eclipse#71]
I created a Run Configuration for a TestNG class to run just a single method from that class.  This configuration will save and then runs correctly - however, when I view it again, the name of the class gets a comma appended to the end, and the method I had chosen disappears.  I can't save or reselect that mehod until I manually delete that comma.

**Comment by missedone** [comment]
closing now, if the issue still on the recent version, create a new ticket then.
