### ISSUE TITLE
Cannot install in Eclipse Kepler

### ISSUE THREAD

**Issue by KellyDC** [cbeust/testng-eclipse#93]
wanting to use this plugin but the site link for update is dead or am I missing something?

**Comment by liefdiy** [comment]
@jonathan-major 
How to export plugin from the project for Kepler ? I have a problem here https://github.com/cbeust/testng-eclipse/issues/134
could you help me ?

**Comment by missedone** [comment]
this issue can be closed as we don't see any problem on eclipse kepler, luna and mars (RC3)
