### ISSUE TITLE
update snakeyaml to 1.12

### ISSUE THREAD

**Issue by jonathan-major** [cbeust/testng-eclipse#94]
hi,

request to update snakeyaml version from 1.6 to 1.12 for testng-eclipse

thanks,
Jonathan

**Comment by apenvern** [comment]
Hello,
I have the same problem with the latest version org.testng.eclipse_6.8.6.20141201_2240. The version of the testng jar is 6.8.7beta-201309140723 and this version of testng use snakeyaml in 1.6.
Thanks
Arnaud
