### ISSUE TITLE
Rerun test method (declared in superclass) should use same class as before

### ISSUE THREAD

**Issue by aledsage** [cbeust/testng-eclipse#98]
If I have classes like:

    public abstract class MySuper {
        `@Test`
        pubilc void testFoo() {}
    }

    public class MySub extends MySuper {
    }

Then after running MySub, if I select testFoo and say to rerun it then it runs zero tests. It tries to run MySuper.testFoo instead, but because that is abstract then it does nothing.

On rerunning tests, it should preserve which class was run as well as which method.

**Comment by missedone** [comment]
fixed in PR #99
